import type {
  PgmlColumn,
  PgmlCompositeType,
  PgmlCustomType,
  PgmlDomainType,
  PgmlEnumType,
  PgmlReference,
  PgmlRoutine,
  PgmlSchemaModel,
  PgmlSequence,
  PgmlTable,
  PgmlTrigger
} from './pgml'

export type PgmlExportFormat = 'sql' | 'kysely'
export type PgmlKyselyTypeStyle = 'pragmatic' | 'strict' | 'loose'

export type PgmlExportPreferences = {
  format: PgmlExportFormat
  kyselyTypeStyle: PgmlKyselyTypeStyle
}

export type PgmlExportArtifact = {
  content: string
  fileName: string
  label: string
  warnings: string[]
}

export type PgmlExportBundle = {
  kysely: {
    interfaces: PgmlExportArtifact
    migration: PgmlExportArtifact
  }
  sql: {
    ddl: PgmlExportArtifact
    migration: PgmlExportArtifact
  }
}

type TypeResolutionContext = {
  customTypesByName: Map<string, PgmlCustomType>
  warnings: Set<string>
}

const defaultExportBaseName = 'pgml-schema'
export const defaultPgmlExportPreferences: PgmlExportPreferences = {
  format: 'sql',
  kyselyTypeStyle: 'pragmatic'
}

const sqlHeader = '-- Generated by PGML diagram export.'
const kyselyMigrationHeader = '// Generated by PGML diagram export.'
const normalizeExportBaseName = (value: string) => {
  const normalized = value
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '')

  return normalized.length > 0 ? normalized : defaultExportBaseName
}

const normalizeNameLookupKey = (value: string) => value.trim().toLowerCase()
const splitQualifiedName = (value: string, defaultSchema = 'public') => {
  const parts = value
    .split('.')
    .map(entry => entry.trim())
    .filter(entry => entry.length > 0)

  if (parts.length <= 1) {
    return {
      schema: defaultSchema,
      name: parts[0] || value.trim()
    }
  }

  return {
    schema: parts.slice(0, -1).join('.'),
    name: parts.at(-1) || value.trim()
  }
}

const quoteSqlIdentifier = (value: string) => `"${value.replaceAll('"', '""')}"`
const formatQualifiedSqlName = (value: string, defaultSchema = 'public') => {
  const { schema, name } = splitQualifiedName(value, defaultSchema)

  return `${quoteSqlIdentifier(schema)}.${quoteSqlIdentifier(name)}`
}

const formatSqlIdentifierList = (values: string[]) => values.map(value => quoteSqlIdentifier(value)).join(', ')
const formatSqlStringLiteral = (value: string) => `'${value.replaceAll('\'', '\'\'')}'`
const ensureSqlStatement = (value: string) => {
  const trimmed = value.trim()

  if (trimmed.length === 0) {
    return ''
  }

  return trimmed.endsWith(';') ? trimmed : `${trimmed};`
}

const escapeTemplateLiteralContent = (value: string) => {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')
}

const getColumnDefaultValue = (column: PgmlColumn) => {
  return column.modifiers.find(modifier => modifier.startsWith('default:'))?.replace('default:', '').trim() || null
}

const getKnownColumnModifiers = (column: PgmlColumn) => {
  return {
    defaultValue: getColumnDefaultValue(column),
    hasPrimaryKey: column.modifiers.includes('pk'),
    hasReference: column.modifiers.some(modifier => modifier.startsWith('ref:')),
    hasUnique: column.modifiers.includes('unique'),
    isNotNull: column.modifiers.includes('not null')
  }
}

const collectUnknownColumnModifiers = (table: PgmlTable, column: PgmlColumn) => {
  const warnings: string[] = []

  column.modifiers.forEach((modifier) => {
    const isKnownModifier = (
      modifier === 'pk'
      || modifier === 'unique'
      || modifier === 'not null'
      || modifier.startsWith('default:')
      || modifier.startsWith('note:')
      || modifier.startsWith('ref:')
      || modifier.startsWith('delete:')
      || modifier.startsWith('update:')
    )

    if (!isKnownModifier) {
      warnings.push(`Column ${table.fullName}.${column.name} uses unsupported modifier "${modifier}" and it was omitted from exports.`)
    }
  })

  return warnings
}

const buildCreateCustomTypeStatement = (customType: PgmlCustomType, warnings: Set<string>) => {
  if (customType.kind === 'Enum') {
    if (!customType.values.length) {
      warnings.add(`Enum ${customType.name} has no values and was omitted from exports.`)
      return null
    }

    return `CREATE TYPE ${formatQualifiedSqlName(customType.name)} AS ENUM (${customType.values.map(value => formatSqlStringLiteral(value)).join(', ')});`
  }

  if (customType.kind === 'Domain') {
    if (!customType.baseType) {
      warnings.add(`Domain ${customType.name} has no base type and was omitted from exports.`)
      return null
    }

    const parts = [
      `CREATE DOMAIN ${formatQualifiedSqlName(customType.name)} AS ${customType.baseType}`
    ]

    if (customType.check) {
      parts.push(`CHECK (${customType.check})`)
    }

    return `${parts.join(' ')};`
  }

  if (!customType.fields.length) {
    warnings.add(`Composite ${customType.name} has no fields and was omitted from exports.`)
    return null
  }

  return `CREATE TYPE ${formatQualifiedSqlName(customType.name)} AS (\n${customType.fields.map(field => `  ${quoteSqlIdentifier(field.name)} ${field.type}`).join(',\n')}\n);`
}

const buildCreateSequenceStatement = (sequence: PgmlSequence) => {
  if (sequence.source) {
    return ensureSqlStatement(sequence.source)
  }

  const metadataByKey = sequence.metadata.reduce<Record<string, string>>((entries, entry) => {
    entries[normalizeNameLookupKey(entry.key)] = entry.value.trim()
    return entries
  }, {})
  const parts = [`CREATE SEQUENCE ${formatQualifiedSqlName(sequence.name)}`]

  if (metadataByKey.as) {
    parts.push(`AS ${metadataByKey.as}`)
  }

  if (metadataByKey.start) {
    parts.push(`START WITH ${metadataByKey.start}`)
  }

  if (metadataByKey.increment) {
    parts.push(`INCREMENT BY ${metadataByKey.increment}`)
  }

  if (metadataByKey.minvalue) {
    parts.push(`MINVALUE ${metadataByKey.minvalue}`)
  }

  if (metadataByKey.maxvalue) {
    parts.push(`MAXVALUE ${metadataByKey.maxvalue}`)
  }

  if (metadataByKey.cache) {
    parts.push(`CACHE ${metadataByKey.cache}`)
  }

  if (metadataByKey.cycle === 'true') {
    parts.push('CYCLE')
  }

  if (metadataByKey.owned_by) {
    parts.push(`OWNED BY ${metadataByKey.owned_by}`)
  }

  return `${parts.join('\n  ')};`
}

const buildCreateTableStatement = (table: PgmlTable, warnings: Set<string>) => {
  const primaryKeyColumns = table.columns
    .filter(column => column.modifiers.includes('pk'))
    .map(column => column.name)
  const lines = table.columns.map((column) => {
    collectUnknownColumnModifiers(table, column).forEach(warning => warnings.add(warning))

    const { defaultValue, hasPrimaryKey, hasUnique, isNotNull } = getKnownColumnModifiers(column)
    const columnParts = [`${quoteSqlIdentifier(column.name)} ${column.type}`]

    if (isNotNull) {
      columnParts.push('NOT NULL')
    }

    if (hasUnique) {
      columnParts.push('UNIQUE')
    }

    if (defaultValue) {
      columnParts.push(`DEFAULT ${defaultValue}`)
    }

    if (primaryKeyColumns.length === 1 && hasPrimaryKey) {
      columnParts.push('PRIMARY KEY')
    }

    return `  ${columnParts.join(' ')}`
  })

  if (primaryKeyColumns.length > 1) {
    lines.push(`  PRIMARY KEY (${formatSqlIdentifierList(primaryKeyColumns)})`)
  }

  table.constraints.forEach((constraint) => {
    const normalizedExpression = constraint.expression.trim()

    if (/^(?:primary key|unique|foreign key|check)\b/i.test(normalizedExpression)) {
      lines.push(`  CONSTRAINT ${quoteSqlIdentifier(constraint.name)} ${normalizedExpression}`)
      return
    }

    lines.push(`  CONSTRAINT ${quoteSqlIdentifier(constraint.name)} CHECK (${constraint.expression})`)
  })

  return `CREATE TABLE ${formatQualifiedSqlName(table.fullName)} (\n${lines.join(',\n')}\n);`
}

const resolveReferenceConstraintParts = (reference: PgmlReference, warnings: Set<string>) => {
  if (reference.relation === '>') {
    return {
      fromColumn: reference.fromColumn,
      fromTable: reference.fromTable,
      onDelete: reference.onDelete,
      onUpdate: reference.onUpdate,
      toColumn: reference.toColumn,
      toTable: reference.toTable
    }
  }

  if (reference.relation === '<') {
    return {
      fromColumn: reference.toColumn,
      fromTable: reference.toTable,
      onDelete: reference.onDelete,
      onUpdate: reference.onUpdate,
      toColumn: reference.fromColumn,
      toTable: reference.fromTable
    }
  }

  warnings.add(`Reference ${reference.fromTable}.${reference.fromColumn} - ${reference.toTable}.${reference.toColumn} was exported as a plain foreign key without adding extra one-to-one uniqueness enforcement.`)

  return {
    fromColumn: reference.fromColumn,
    fromTable: reference.fromTable,
    onDelete: reference.onDelete,
    onUpdate: reference.onUpdate,
    toColumn: reference.toColumn,
    toTable: reference.toTable
  }
}

const buildReferenceActionClause = (keyword: 'DELETE' | 'UPDATE', action: string | null) => {
  if (!action || action.trim().length === 0) {
    return ''
  }

  return ` ON ${keyword} ${action.trim().toUpperCase()}`
}

const buildReferenceStatements = (references: PgmlReference[], warnings: Set<string>) => {
  const seen = new Set<string>()

  return references.reduce<string[]>((statements, reference) => {
    const normalized = resolveReferenceConstraintParts(reference, warnings)
    const key = [
      normalizeNameLookupKey(normalized.fromTable),
      normalizeNameLookupKey(normalized.fromColumn),
      normalizeNameLookupKey(normalized.toTable),
      normalizeNameLookupKey(normalized.toColumn),
      normalizeNameLookupKey(normalized.onDelete || ''),
      normalizeNameLookupKey(normalized.onUpdate || '')
    ].join('::')

    if (seen.has(key)) {
      return statements
    }

    seen.add(key)
    statements.push(
      `ALTER TABLE ${formatQualifiedSqlName(normalized.fromTable)} ADD FOREIGN KEY (${quoteSqlIdentifier(normalized.fromColumn)}) REFERENCES ${formatQualifiedSqlName(normalized.toTable)} (${quoteSqlIdentifier(normalized.toColumn)})${buildReferenceActionClause('DELETE', normalized.onDelete)}${buildReferenceActionClause('UPDATE', normalized.onUpdate)};`
    )
    return statements
  }, [])
}

const buildIndexStatement = (table: PgmlTable, indexName: string, columns: string[], indexType: string) => {
  return `CREATE INDEX ${quoteSqlIdentifier(indexName)} ON ${formatQualifiedSqlName(table.fullName)} USING ${indexType} (${formatSqlIdentifierList(columns)});`
}

const buildExecutableSourceStatement = (
  kind: 'Function' | 'Procedure' | 'Trigger',
  executable: PgmlRoutine | PgmlTrigger,
  warnings: Set<string>
) => {
  if (executable.source) {
    return ensureSqlStatement(executable.source)
  }

  warnings.add(`${kind} ${executable.name} has no source block and was omitted from exports.`)
  return null
}

const buildSqlStatements = (model: PgmlSchemaModel) => {
  const warnings = new Set<string>()
  const statements: string[] = []

  model.customTypes.forEach((customType) => {
    const statement = buildCreateCustomTypeStatement(customType, warnings)

    if (statement) {
      statements.push(statement)
    }
  })

  model.sequences.forEach((sequence) => {
    statements.push(buildCreateSequenceStatement(sequence))
  })

  model.tables.forEach((table) => {
    statements.push(buildCreateTableStatement(table, warnings))
  })

  buildReferenceStatements(model.references, warnings).forEach(statement => statements.push(statement))

  model.tables.forEach((table) => {
    table.indexes.forEach((index) => {
      statements.push(buildIndexStatement(table, index.name, index.columns, index.type || 'btree'))
    })
  })

  model.functions.forEach((pgFunction) => {
    const statement = buildExecutableSourceStatement('Function', pgFunction, warnings)

    if (statement) {
      statements.push(statement)
    }
  })

  model.procedures.forEach((procedure) => {
    const statement = buildExecutableSourceStatement('Procedure', procedure, warnings)

    if (statement) {
      statements.push(statement)
    }
  })

  model.triggers.forEach((trigger) => {
    const statement = buildExecutableSourceStatement('Trigger', trigger, warnings)

    if (statement) {
      statements.push(statement)
    }
  })

  return {
    statements,
    warnings: Array.from(warnings)
  }
}

const createCustomTypeLookup = (customTypes: PgmlCustomType[]) => {
  const map = new Map<string, PgmlCustomType>()

  customTypes.forEach((customType) => {
    const fullKey = normalizeNameLookupKey(customType.name)
    const shortKey = normalizeNameLookupKey(splitQualifiedName(customType.name).name)

    map.set(fullKey, customType)
    map.set(shortKey, customType)
  })

  return map
}

const toPascalCase = (value: string) => {
  const normalized = value
    .replaceAll(/_/g, ' ')
    .replaceAll(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')

  if (normalized.length === 0) {
    return 'PgmlValue'
  }

  return /^[A-Z_]/.test(normalized) ? normalized : `Pgml${normalized}`
}

const getCustomTypeSymbolName = (customType: PgmlCustomType) => {
  const { schema, name } = splitQualifiedName(customType.name)
  return schema === 'public'
    ? toPascalCase(name)
    : toPascalCase(`${schema} ${name}`)
}

const getTableInterfaceName = (table: PgmlTable) => {
  return splitQualifiedName(table.fullName).schema === 'public'
    ? `${toPascalCase(table.name)}Table`
    : `${toPascalCase(`${table.schema} ${table.name}`)}Table`
}

const getBaseTypeAndArrayDepth = (value: string) => {
  let normalized = value.trim()
  let arrayDepth = 0

  while (normalized.endsWith('[]')) {
    arrayDepth += 1
    normalized = normalized.slice(0, -2).trim()
  }

  return {
    arrayDepth,
    baseType: normalized
  }
}

const wrapArrayType = (value: string, depth: number) => {
  let result = value

  for (let index = 0; index < depth; index += 1) {
    result = `Array<${result}>`
  }

  return result
}

const resolveBuiltInType = (rawType: string, style: PgmlKyselyTypeStyle) => {
  const normalized = rawType
    .trim()
    .toLowerCase()
    .replace(/\(.+\)$/, '')
    .replace(/\s+/g, ' ')

  const numericType = style === 'strict' ? 'string' : 'number'

  if (['boolean', 'bool'].includes(normalized)) {
    return 'boolean'
  }

  if (['smallint', 'integer', 'int', 'int2', 'int4', 'serial', 'smallserial'].includes(normalized)) {
    return 'number'
  }

  if (['bigint', 'int8', 'bigserial', 'numeric', 'decimal', 'money', 'real', 'float4', 'float8', 'double precision'].includes(normalized)) {
    return numericType
  }

  if (['json', 'jsonb'].includes(normalized)) {
    return style === 'loose' ? 'unknown' : 'JsonValue'
  }

  if (['bytea'].includes(normalized)) {
    return style === 'loose' ? 'unknown' : 'Uint8Array'
  }

  if ([
    'uuid',
    'text',
    'varchar',
    'character varying',
    'char',
    'character',
    'citext',
    'date',
    'time',
    'timetz',
    'timestamp',
    'timestamptz',
    'interval',
    'tsvector',
    'inet',
    'cidr',
    'macaddr',
    'xml'
  ].includes(normalized)) {
    return 'string'
  }

  return null
}

const resolveTypeScriptType = (
  rawType: string,
  style: PgmlKyselyTypeStyle,
  context: TypeResolutionContext,
  domainStack: string[] = []
) => {
  const { arrayDepth, baseType } = getBaseTypeAndArrayDepth(rawType)
  const builtInType = resolveBuiltInType(baseType, style)

  if (builtInType) {
    return wrapArrayType(builtInType, arrayDepth)
  }

  const customType = context.customTypesByName.get(normalizeNameLookupKey(baseType))

  if (customType?.kind === 'Enum') {
    return wrapArrayType(getCustomTypeSymbolName(customType), arrayDepth)
  }

  if (customType?.kind === 'Composite') {
    return wrapArrayType(getCustomTypeSymbolName(customType), arrayDepth)
  }

  if (customType?.kind === 'Domain') {
    const customTypeKey = normalizeNameLookupKey(customType.name)

    if (domainStack.includes(customTypeKey)) {
      context.warnings.add(`Domain ${customType.name} has a circular base-type reference and was emitted as unknown.`)
      return wrapArrayType('unknown', arrayDepth)
    }

    return wrapArrayType(getCustomTypeSymbolName(customType), arrayDepth)
  }

  if (style === 'loose') {
    context.warnings.add(`Type ${rawType} is not mapped explicitly and was emitted as unknown in Kysely interfaces.`)
    return wrapArrayType('unknown', arrayDepth)
  }

  context.warnings.add(`Type ${rawType} is not mapped explicitly and was emitted as string in Kysely interfaces.`)
  return wrapArrayType('string', arrayDepth)
}

const applyColumnTypeWrappers = (value: string, column: PgmlColumn) => {
  const { defaultValue, hasPrimaryKey } = getKnownColumnModifiers(column)
  const isGenerated = Boolean(defaultValue) || ['serial', 'bigserial', 'smallserial'].includes(column.type.trim().toLowerCase())
  const isNullable = !column.modifiers.includes('not null') && !hasPrimaryKey
  let resolvedType = value

  if (isNullable) {
    resolvedType = `${resolvedType} | null`
  }

  if (isGenerated) {
    resolvedType = `Generated<${resolvedType}>`
  }

  return resolvedType
}

const buildEnumTypeDefinition = (customType: PgmlEnumType) => {
  return `export type ${getCustomTypeSymbolName(customType)} = ${customType.values.map(value => formatSqlStringLiteral(value)).join(' | ')}`
}

const buildDomainTypeDefinition = (
  customType: PgmlDomainType,
  style: PgmlKyselyTypeStyle,
  context: TypeResolutionContext
) => {
  const resolvedBaseType = customType.baseType
    ? resolveTypeScriptType(customType.baseType, style, context, [normalizeNameLookupKey(customType.name)])
    : 'unknown'

  if (!customType.baseType) {
    context.warnings.add(`Domain ${customType.name} has no base type and was emitted as unknown in Kysely interfaces.`)
  }

  return `export type ${getCustomTypeSymbolName(customType)} = ${resolvedBaseType}`
}

const buildCompositeTypeDefinition = (
  customType: PgmlCompositeType,
  style: PgmlKyselyTypeStyle,
  context: TypeResolutionContext
) => {
  if (!customType.fields.length) {
    context.warnings.add(`Composite ${customType.name} has no fields and was emitted as an empty interface in Kysely interfaces.`)
  }

  return [
    `export interface ${getCustomTypeSymbolName(customType)} {`,
    ...customType.fields.map((field) => {
      return `  ${quoteSqlIdentifier(field.name).replaceAll('"', '')}: ${resolveTypeScriptType(field.type, style, context)}`
    }),
    '}'
  ].join('\n')
}

const buildTableInterfaceDefinition = (
  table: PgmlTable,
  style: PgmlKyselyTypeStyle,
  context: TypeResolutionContext
) => {
  return [
    `export interface ${getTableInterfaceName(table)} {`,
    ...table.columns.map((column) => {
      const resolvedType = applyColumnTypeWrappers(resolveTypeScriptType(column.type, style, context), column)
      return `  ${quoteSqlIdentifier(column.name).replaceAll('"', '')}: ${resolvedType}`
    }),
    '}'
  ].join('\n')
}

const buildJsonHelperBlock = (content: string) => {
  if (!content.includes('JsonValue')) {
    return null
  }

  return [
    'export type JsonPrimitive = boolean | null | number | string',
    'export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue }'
  ].join('\n')
}

const buildKyselyInterfacesContent = (
  model: PgmlSchemaModel,
  style: PgmlKyselyTypeStyle
) => {
  const warnings = new Set<string>()
  const context: TypeResolutionContext = {
    customTypesByName: createCustomTypeLookup(model.customTypes),
    warnings
  }
  const customTypeBlocks = model.customTypes.map((customType) => {
    if (customType.kind === 'Enum') {
      return buildEnumTypeDefinition(customType)
    }

    if (customType.kind === 'Domain') {
      return buildDomainTypeDefinition(customType, style, context)
    }

    return buildCompositeTypeDefinition(customType, style, context)
  })
  const tableBlocks = model.tables.map(table => buildTableInterfaceDefinition(table, style, context))
  const databaseBlock = [
    'export interface Database {',
    ...model.tables.map((table) => {
      return `  '${table.fullName}': ${getTableInterfaceName(table)}`
    }),
    '}'
  ].join('\n')
  const body = [
    '// Generated by PGML diagram export.',
    'import type { Generated } from \'kysely\'',
    buildJsonHelperBlock([...customTypeBlocks, ...tableBlocks].join('\n\n')),
    ...customTypeBlocks,
    ...tableBlocks,
    databaseBlock
  ].filter(section => typeof section === 'string' && section.trim().length > 0)

  return {
    content: `${body.join('\n\n')}\n`,
    warnings: Array.from(warnings)
  }
}

const buildKyselyMigrationContent = (
  baseName: string,
  statements: string[]
) => {
  const statementBlocks = statements.map((statement) => {
    return `  await sql\`
${escapeTemplateLiteralContent(statement)}
\`.execute(db)`
  }).join('\n\n')

  return `${kyselyMigrationHeader}
import type { Kysely } from 'kysely'
import { sql } from 'kysely'
import type { Database } from './${baseName}.database'

export const up = async (db: Kysely<Database>): Promise<void> => {
${statementBlocks}
}

export const down = async (): Promise<void> => {
  throw new Error('PGML exports generate forward-only migrations. Write the down migration manually.')
}
`
}

const buildSqlRawDdlContent = (statements: string[]) => {
  return `${sqlHeader}\n\n${statements.join('\n\n')}\n`
}

const buildSqlMigrationContent = (statements: string[]) => {
  return `${sqlHeader}\n\nBEGIN;\n\n${statements.join('\n\n')}\n\nCOMMIT;\n`
}

export const buildPgmlExportBundle = (
  model: PgmlSchemaModel,
  options: {
    baseName?: string
    kyselyTypeStyle: PgmlKyselyTypeStyle
  }
): PgmlExportBundle => {
  const normalizedBaseName = normalizeExportBaseName(options.baseName || defaultExportBaseName)
  const { statements, warnings: sqlWarnings } = buildSqlStatements(model)
  const kyselyInterfaces = buildKyselyInterfacesContent(model, options.kyselyTypeStyle)
  const kyselyMigrationWarnings = Array.from(new Set([
    ...sqlWarnings
  ]))

  return {
    kysely: {
      interfaces: {
        content: kyselyInterfaces.content,
        fileName: `${normalizedBaseName}.database.ts`,
        label: 'Database Interfaces',
        warnings: kyselyInterfaces.warnings
      },
      migration: {
        content: buildKyselyMigrationContent(normalizedBaseName, statements),
        fileName: `${normalizedBaseName}.migration.ts`,
        label: 'Migration',
        warnings: kyselyMigrationWarnings
      }
    },
    sql: {
      ddl: {
        content: buildSqlRawDdlContent(statements),
        fileName: `${normalizedBaseName}.ddl.sql`,
        label: 'Raw DDL',
        warnings: sqlWarnings
      },
      migration: {
        content: buildSqlMigrationContent(statements),
        fileName: `${normalizedBaseName}.migration.sql`,
        label: 'Migration SQL',
        warnings: sqlWarnings
      }
    }
  }
}
