import type { PgmlExportArtifact } from './pgml-export'
import {
  getNormalizedPgmlColumnDefaultModifierValue,
  normalizePgmlColumnModifiers
} from './pgml-column-modifiers'
import {
  buildPgmlImplicitSerialSequenceName,
  createPgmlCompareTypeExpressionNormalizer,
  normalizePgmlCompareColumnValue,
  normalizePgmlCompareConstraintExpression,
  normalizePgmlCompareCustomTypeName,
  normalizePgmlCompareRoutinePairValues,
  normalizePgmlCompareSequenceMetadataEntries,
  normalizePgmlCompareSequenceValue,
  normalizePgmlCompareTriggerValue
} from './pgml-compare-normalization'
import { normalizeImportedQualifiedName } from './pgml-import-normalization'
import type {
  PgmlColumn,
  PgmlCompositeType,
  PgmlConstraint,
  PgmlCustomType,
  PgmlEnumType,
  PgmlIndex,
  PgmlReference,
  PgmlRoutine,
  PgmlSchemaModel,
  PgmlSequence,
  PgmlTable,
  PgmlTrigger
} from './pgml'

export type PgmlMigrationDiffBundle = {
  meta: {
    hasChanges: boolean
    statementCount: number
    warningCount: number
  }
  kysely: {
    migration: PgmlExportArtifact
  }
  sql: {
    migration: PgmlExportArtifact
  }
}

export type PgmlMigrationDiffPlan = {
  statements: string[]
  warnings: string[]
}

type PgmlMigrationStatementPhases = {
  // Cleanup that must happen after new schema objects exist, such as re-adding
  // dependents or finalizing dependency-sensitive statements.
  postDependencyCleanup: string[]
  // Follow-up statements that rely on table bodies already being in place.
  postTableStatements: string[]
  // Dependency removals must happen before destructive table edits.
  preDependencyDrops: string[]
  // Preparations such as creating prerequisite types or sequences happen here.
  preTablePreparations: string[]
  // Direct table create/alter/drop operations are grouped in the middle phase.
  tableStatements: string[]
}

type PgmlTableAlterPlan = {
  postAlterStatements: string[]
  preAlterStatements: string[]
  tableStatements: string[]
}

const kyselyMigrationHeader = '// Generated by PGML version diff.'
const sqlHeader = '-- Generated by PGML version diff.'
const toStableJson = (value: unknown): string => {
  if (Array.isArray(value)) {
    return `[${value.map(entry => toStableJson(entry)).join(',')}]`
  }

  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, entry]) => entry !== undefined)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, entry]) => `"${key}":${toStableJson(entry)}`)

    return `{${entries.join(',')}}`
  }

  return JSON.stringify(value)
}
const normalizeExportBaseName = (value: string) => {
  const normalized = value
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '')

  return normalized.length > 0 ? normalized : 'pgml-version'
}

const splitQualifiedName = (value: string, defaultSchema = 'public') => {
  const parts = value
    .split('.')
    .map(entry => entry.trim())
    .filter(entry => entry.length > 0)

  if (parts.length <= 1) {
    return {
      name: parts[0] || value.trim(),
      schema: defaultSchema
    }
  }

  return {
    name: parts.at(-1) || value.trim(),
    schema: parts.slice(0, -1).join('.')
  }
}

const quoteSqlIdentifier = (value: string) => `"${value.replaceAll('"', '""')}"`

const formatQualifiedSqlName = (value: string, defaultSchema = 'public') => {
  const { name, schema } = splitQualifiedName(value, defaultSchema)

  return `${quoteSqlIdentifier(schema)}.${quoteSqlIdentifier(name)}`
}

const formatSqlIdentifierList = (values: string[]) => values.map(value => quoteSqlIdentifier(value)).join(', ')
const quoteSqlLiteral = (value: string) => `'${value.replaceAll('\'', '\'\'')}'`
const createEmptyMigrationStatementPhases = (): PgmlMigrationStatementPhases => {
  return {
    postDependencyCleanup: [],
    postTableStatements: [],
    preDependencyDrops: [],
    preTablePreparations: [],
    tableStatements: []
  }
}
const isSubsequence = (candidate: string[], target: string[]) => {
  let targetIndex = 0

  for (const entry of candidate) {
    while (targetIndex < target.length && target[targetIndex] !== entry) {
      targetIndex += 1
    }

    if (targetIndex >= target.length) {
      return false
    }

    targetIndex += 1
  }

  return true
}
const finalizeMigrationStatements = (phases: PgmlMigrationStatementPhases) => {
  // The final order keeps destructive dependency drops ahead of table changes
  // and reintroduces dependent objects only after their prerequisites exist.
  const orderedStatements = [
    ...phases.preDependencyDrops,
    ...phases.preTablePreparations,
    ...phases.tableStatements,
    ...phases.postTableStatements,
    ...phases.postDependencyCleanup
  ]
  const seenStatements = new Set<string>()

  return orderedStatements.flatMap((statement) => {
    const normalizedStatement = ensureSqlStatement(statement)

    if (normalizedStatement.length === 0 || seenStatements.has(normalizedStatement)) {
      return []
    }

    seenStatements.add(normalizedStatement)

    return [normalizedStatement]
  })
}

const ensureSqlStatement = (value: string) => {
  const trimmed = value.trim()

  if (trimmed.length === 0) {
    return ''
  }

  return trimmed.endsWith(';') ? trimmed : `${trimmed};`
}

const escapeTemplateLiteralContent = (value: string) => {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')
}

const buildKyselyStatementBlock = (statement: string) => {
  // Keeping the template-literal block in one helper makes it easier to update
  // escaping or execution semantics without touching every artifact builder.
  return `  await sql\`
${escapeTemplateLiteralContent(statement)}
\`.execute(db)`
}

const buildKyselyMigrationContent = (
  baseName: string,
  statements: string[]
) => {
  // Kysely exports intentionally mirror the SQL statement order one-for-one so
  // history-aware validation can compare the two artifacts mechanically.
  const statementBlocks = statements.map(statement => buildKyselyStatementBlock(statement)).join('\n\n')

  return `${kyselyMigrationHeader}
import type { Kysely } from 'kysely'
import { sql } from 'kysely'
import type { Database } from './${baseName}.database'

export const up = async (db: Kysely<Database>): Promise<void> => {
${statementBlocks}
}

export const down = async (): Promise<void> => {
  throw new Error('PGML exports generate forward-only migrations. Write the down migration manually.')
}
`
}

const buildSqlMigrationContent = (statements: string[]) => {
  return `${sqlHeader}\n\nBEGIN;\n\n${statements.join('\n\n')}\n\nCOMMIT;\n`
}

export const buildPgmlMigrationArtifactsFromPlan = (
  plan: PgmlMigrationDiffPlan,
  options: {
    baseName?: string
  } = {}
): PgmlMigrationDiffBundle => {
  // The artifact bundle is the shared currency between direct diffs and
  // history-aware version exports, so SQL/Kysely metadata stays aligned here.
  const baseName = normalizeExportBaseName(options.baseName || 'pgml-version')

  return {
    kysely: {
      migration: {
        content: buildKyselyMigrationContent(baseName, plan.statements),
        fileName: `${baseName}.migration.ts`,
        label: 'Version Migration',
        warnings: [...plan.warnings]
      }
    },
    meta: {
      hasChanges: plan.statements.length > 0,
      statementCount: plan.statements.length,
      warningCount: plan.warnings.length
    },
    sql: {
      migration: {
        content: buildSqlMigrationContent(plan.statements),
        fileName: `${baseName}.migration.sql`,
        label: 'Version Migration SQL',
        warnings: [...plan.warnings]
      }
    }
  }
}

const buildReferenceActionClause = (keyword: 'DELETE' | 'UPDATE', action: string | null) => {
  if (!action || action.trim().length === 0) {
    return ''
  }

  return ` ON ${keyword} ${action.trim().toUpperCase()}`
}

const getColumnDefaultValue = (column: PgmlColumn) => {
  return column.modifiers.find(modifier => modifier.startsWith('default:'))?.replace('default:', '').trim() || null
}

const buildColumnDefinition = (column: PgmlColumn) => {
  const columnParts = [`${quoteSqlIdentifier(column.name)} ${column.type}`]

  if (column.modifiers.includes('not null')) {
    columnParts.push('NOT NULL')
  }

  if (column.modifiers.includes('unique')) {
    columnParts.push('UNIQUE')
  }

  if (column.modifiers.includes('pk')) {
    columnParts.push('PRIMARY KEY')
  }

  const defaultValue = getColumnDefaultValue(column)

  if (defaultValue) {
    columnParts.push(`DEFAULT ${defaultValue}`)
  }

  return columnParts.join(' ')
}

const buildCreateTableStatement = (table: PgmlTable) => {
  const primaryKeyColumns = table.columns
    .filter(column => column.modifiers.includes('pk'))
    .map(column => column.name)
  const lines = table.columns.map((column) => {
    const columnParts = [`${quoteSqlIdentifier(column.name)} ${column.type}`]

    if (column.modifiers.includes('not null')) {
      columnParts.push('NOT NULL')
    }

    if (column.modifiers.includes('unique')) {
      columnParts.push('UNIQUE')
    }

    const defaultValue = getColumnDefaultValue(column)

    if (defaultValue) {
      columnParts.push(`DEFAULT ${defaultValue}`)
    }

    if (primaryKeyColumns.length === 1 && column.modifiers.includes('pk')) {
      columnParts.push('PRIMARY KEY')
    }

    return `  ${columnParts.join(' ')}`
  })

  if (primaryKeyColumns.length > 1) {
    lines.push(`  PRIMARY KEY (${formatSqlIdentifierList(primaryKeyColumns)})`)
  }

  table.constraints.forEach((constraint) => {
    const normalizedExpression = constraint.expression.trim()

    if (/^(?:primary key|unique|foreign key|check)\b/i.test(normalizedExpression)) {
      lines.push(`  CONSTRAINT ${quoteSqlIdentifier(constraint.name)} ${normalizedExpression}`)
      return
    }

    lines.push(`  CONSTRAINT ${quoteSqlIdentifier(constraint.name)} CHECK (${constraint.expression})`)
  })

  return `CREATE TABLE ${formatQualifiedSqlName(table.fullName)} (\n${lines.join(',\n')}\n);`
}

const buildCreateIndexStatement = (tableId: string, index: PgmlIndex) => {
  return `CREATE INDEX ${quoteSqlIdentifier(index.name)} ON ${formatQualifiedSqlName(tableId)} USING ${index.type || 'btree'} (${formatSqlIdentifierList(index.columns)});`
}

const buildCreateReferenceStatement = (reference: PgmlReference) => {
  const fromColumns = reference.fromColumns && reference.fromColumns.length > 0
    ? reference.fromColumns
    : [reference.fromColumn]
  const toColumns = reference.toColumns && reference.toColumns.length > 0
    ? reference.toColumns
    : [reference.toColumn]

  return `ALTER TABLE ${formatQualifiedSqlName(reference.fromTable)} ADD FOREIGN KEY (${formatSqlIdentifierList(fromColumns)}) REFERENCES ${formatQualifiedSqlName(reference.toTable)} (${formatSqlIdentifierList(toColumns)})${buildReferenceActionClause('DELETE', reference.onDelete)}${buildReferenceActionClause('UPDATE', reference.onUpdate)};`
}

const buildDropReferenceStatement = (reference: PgmlReference) => {
  const { name: tableName } = splitQualifiedName(reference.fromTable)
  const fromColumns = reference.fromColumns && reference.fromColumns.length > 0
    ? reference.fromColumns
    : [reference.fromColumn]
  const constraintName = `${tableName}_${fromColumns.join('_')}_fkey`

  return `ALTER TABLE ${formatQualifiedSqlName(reference.fromTable)} DROP CONSTRAINT IF EXISTS ${quoteSqlIdentifier(constraintName)};`
}

const buildCreateCustomTypeStatement = (customType: PgmlCustomType) => {
  if (customType.kind === 'Enum') {
    return `CREATE TYPE ${formatQualifiedSqlName(customType.name)} AS ENUM (${customType.values.map(value => `'${value.replaceAll('\'', '\'\'')}'`).join(', ')});`
  }

  if (customType.kind === 'Domain') {
    const parts = [`CREATE DOMAIN ${formatQualifiedSqlName(customType.name)} AS ${customType.baseType || 'text'}`]

    if (customType.check) {
      parts.push(`CHECK (${customType.check})`)
    }

    return `${parts.join(' ')};`
  }

  return `CREATE TYPE ${formatQualifiedSqlName(customType.name)} AS (\n${customType.fields.map(field => `  ${quoteSqlIdentifier(field.name)} ${field.type}`).join(',\n')}\n);`
}

const buildDropCustomTypeStatement = (customType: PgmlCustomType) => {
  if (customType.kind === 'Domain') {
    return `DROP DOMAIN IF EXISTS ${formatQualifiedSqlName(customType.name)};`
  }

  return `DROP TYPE IF EXISTS ${formatQualifiedSqlName(customType.name)};`
}

const buildCreateSequenceStatement = (sequence: PgmlSequence) => {
  if (sequence.source) {
    return ensureSqlStatement(sequence.source)
  }

  return `CREATE SEQUENCE ${formatQualifiedSqlName(sequence.name)};`
}

const buildDropSequenceStatement = (sequence: PgmlSequence) => {
  return `DROP SEQUENCE IF EXISTS ${formatQualifiedSqlName(sequence.name)};`
}

const buildRoutineMap = (routines: PgmlRoutine[]) => {
  return new Map(routines.map(routine => [normalizeRoutineKey(routine.name), routine] as const))
}

const buildSequenceMap = (sequences: PgmlSequence[]) => {
  return new Map(sequences.map(sequence => [sequence.name, sequence] as const))
}

const buildCustomTypeMap = (
  customTypes: PgmlCustomType[],
  normalizeType: (value: string) => string
) => {
  return new Map(customTypes.map((customType) => {
    return [
      `${customType.kind}::${normalizePgmlCompareCustomTypeName(customType.name, normalizeType)}`,
      customType
    ] as const
  }))
}

const buildTableMap = (tables: PgmlTable[]) => {
  return new Map(tables.map(table => [table.fullName, table] as const))
}

const buildReferenceMap = (references: PgmlReference[]) => {
  return new Map(references.map(reference => [[
    reference.fromTable,
    (reference.fromColumns && reference.fromColumns.length > 0 ? reference.fromColumns : [reference.fromColumn]).join(','),
    reference.relation,
    reference.toTable,
    (reference.toColumns && reference.toColumns.length > 0 ? reference.toColumns : [reference.toColumn]).join(',')
  ].join('::'), reference] as const))
}

const buildIndexMap = (table: PgmlTable) => {
  return new Map(table.indexes.map(index => [index.name, index] as const))
}

const buildConstraintMap = (table: PgmlTable) => {
  return new Map(table.constraints.map(constraint => [constraint.name, constraint] as const))
}

const buildColumnMap = (table: PgmlTable) => {
  return new Map(table.columns.map(column => [column.name, column] as const))
}

const buildOwnedByColumnId = (value: string) => {
  const separatorIndex = value.lastIndexOf('.')

  if (separatorIndex < 0) {
    return null
  }

  return {
    columnName: value.slice(separatorIndex + 1),
    tableId: value.slice(0, separatorIndex)
  }
}

const isSerialPseudoType = (value: string) => {
  return ['bigserial', 'serial', 'serial2', 'serial4', 'serial8', 'smallserial'].includes(value.trim().toLowerCase())
}

const isImplicitSerialSequenceValue = (input: {
  column: {
    column: PgmlColumn
    tableId: string
  }
  normalizeType: (value: string) => string
  sequence: PgmlSequence
}) => {
  if (
    input.sequence.docs
    || input.sequence.affects
    || (input.sequence.source?.trim().length || 0) > 0
  ) {
    return false
  }

  const expectedSequenceName = buildPgmlImplicitSerialSequenceName(
    input.column.tableId,
    input.column.column.name
  )

  if (input.sequence.name !== expectedSequenceName) {
    return false
  }

  const normalizedColumn = normalizePgmlCompareColumnValue({
    column: input.column.column,
    normalizeType: input.normalizeType,
    tableId: input.column.tableId
  })
  const normalizedDefault = normalizedColumn.modifiers.find(modifier => modifier.startsWith('default:'))
    ?.replace(/^default:\s*/u, '')
    .trim()

  if (normalizedDefault !== `nextval('${expectedSequenceName}')`) {
    return false
  }

  const normalizedSequenceMetadata = normalizePgmlCompareSequenceMetadataEntries(
    input.sequence.metadata,
    input.normalizeType
  )
  const expectedMetadata = normalizePgmlCompareSequenceMetadataEntries([
    {
      key: 'as',
      value: normalizedColumn.type
    },
    {
      key: 'owned_by',
      value: `${input.column.tableId}.${input.column.column.name}`
    }
  ], input.normalizeType)

  return toStableJson(normalizedSequenceMetadata) === toStableJson(expectedMetadata)
}

const isImplicitSerialSequenceOnlyDiff = (input: {
  afterTables: Map<string, PgmlTable>
  beforeTables: Map<string, PgmlTable>
  normalizeType: (value: string) => string
  sequence: PgmlSequence
  type: 'added' | 'removed'
}) => {
  const normalizedMetadata = normalizePgmlCompareSequenceMetadataEntries(
    input.sequence.metadata,
    input.normalizeType
  )
  const ownedBy = normalizedMetadata.find(entry => entry.key === 'owned_by')?.value || null

  if (!ownedBy) {
    return false
  }

  const ownedByColumn = buildOwnedByColumnId(ownedBy)

  if (!ownedByColumn) {
    return false
  }

  const beforeTable = input.beforeTables.get(ownedByColumn.tableId) || null
  const afterTable = input.afterTables.get(ownedByColumn.tableId) || null

  if (!beforeTable || !afterTable) {
    return false
  }

  const beforeColumn = buildColumnMap(beforeTable).get(ownedByColumn.columnName) || null
  const afterColumn = buildColumnMap(afterTable).get(ownedByColumn.columnName) || null

  if (!beforeColumn || !afterColumn) {
    return false
  }

  const normalizedBeforeColumn = normalizePgmlCompareColumnValue({
    column: beforeColumn,
    normalizeType: input.normalizeType,
    tableId: beforeTable.fullName
  })
  const normalizedAfterColumn = normalizePgmlCompareColumnValue({
    column: afterColumn,
    normalizeType: input.normalizeType,
    tableId: afterTable.fullName
  })

  if (toStableJson(normalizedBeforeColumn) !== toStableJson(normalizedAfterColumn)) {
    return false
  }

  if (input.type === 'added' && !isSerialPseudoType(beforeColumn.type)) {
    return false
  }

  if (input.type === 'removed' && !isSerialPseudoType(afterColumn.type)) {
    return false
  }

  return isImplicitSerialSequenceValue({
    column: input.type === 'added'
      ? {
          column: afterColumn,
          tableId: afterTable.fullName
        }
      : {
          column: beforeColumn,
          tableId: beforeTable.fullName
        },
    normalizeType: input.normalizeType,
    sequence: input.sequence
  })
}

const normalizeIndexForCompare = (index: PgmlIndex) => {
  return {
    columns: index.columns,
    name: index.name,
    type: index.type
  }
}

const normalizeConstraintForCompare = (constraint: PgmlConstraint) => {
  return {
    expression: normalizePgmlCompareConstraintExpression(constraint.expression),
    name: constraint.name
  }
}

const normalizeReferenceForCompare = (reference: PgmlReference) => {
  return {
    fromColumn: reference.fromColumn,
    fromColumns: reference.fromColumns && reference.fromColumns.length > 0 ? [...reference.fromColumns] : [reference.fromColumn],
    fromTable: reference.fromTable,
    onDelete: reference.onDelete,
    onUpdate: reference.onUpdate,
    relation: reference.relation,
    toColumn: reference.toColumn,
    toColumns: reference.toColumns && reference.toColumns.length > 0 ? [...reference.toColumns] : [reference.toColumn],
    toTable: reference.toTable
  }
}

const normalizeRoutineKey = (value: string) => {
  const normalizedValue = normalizeImportedQualifiedName(value, {
    foldIdentifiersToLowercase: true
  })

  return normalizedValue.startsWith('public.')
    ? normalizedValue.slice('public.'.length)
    : normalizedValue
}

const normalizeTriggerForCompare = (trigger: PgmlTrigger) => {
  return normalizePgmlCompareTriggerValue(trigger)
}

const normalizeTriggerTableKey = (value: string) => {
  const normalizedValue = normalizeImportedQualifiedName(value, {
    foldIdentifiersToLowercase: true
  })

  return normalizedValue.startsWith('public.')
    ? normalizedValue.slice('public.'.length)
    : normalizedValue
}

const normalizeSequenceForCompare = (
  sequence: PgmlSequence,
  normalizeType: (value: string) => string
) => {
  return normalizePgmlCompareSequenceValue(sequence, normalizeType)
}

const normalizeCustomTypeForCompare = (
  customType: PgmlCustomType,
  normalizeType: (value: string) => string
) => {
  if (customType.kind === 'Enum') {
    return {
      kind: customType.kind,
      name: normalizePgmlCompareCustomTypeName(customType.name, normalizeType),
      values: customType.values
    }
  }

  if (customType.kind === 'Domain') {
    return {
      baseType: customType.baseType ? normalizeType(customType.baseType) : null,
      check: customType.check,
      kind: customType.kind,
      name: normalizePgmlCompareCustomTypeName(customType.name, normalizeType)
    }
  }

  return {
    fields: customType.fields.map((field) => {
      return {
        ...field,
        type: normalizeType(field.type)
      }
    }),
    kind: customType.kind,
    name: normalizePgmlCompareCustomTypeName(customType.name, normalizeType)
  }
}

const buildEnumAlterStatements = (
  beforeType: PgmlEnumType,
  afterType: PgmlEnumType,
  warnings: Set<string>
) => {
  if (!isSubsequence(beforeType.values, afterType.values)) {
    warnings.add(`Enum ${beforeType.name} changed in a way that cannot be migrated safely with ALTER TYPE. Generate the enum migration manually.`)
    return []
  }

  const currentValues = [...beforeType.values]
  const statements: string[] = []

  afterType.values.forEach((value, index) => {
    if (currentValues.includes(value)) {
      return
    }

    const previousValue = afterType.values
      .slice(0, index)
      .reverse()
      .find(entry => currentValues.includes(entry)) || null
    const nextValue = afterType.values
      .slice(index + 1)
      .find(entry => currentValues.includes(entry)) || null
    const positionClause = nextValue
      ? ` BEFORE ${quoteSqlLiteral(nextValue)}`
      : previousValue
        ? ` AFTER ${quoteSqlLiteral(previousValue)}`
        : ''

    statements.push(
      `ALTER TYPE ${formatQualifiedSqlName(afterType.name)} ADD VALUE IF NOT EXISTS ${quoteSqlLiteral(value)}${positionClause};`
    )
    currentValues.splice(index, 0, value)
  })

  return statements
}

const buildCompositeAlterStatements = (
  beforeType: PgmlCompositeType,
  afterType: PgmlCompositeType,
  warnings: Set<string>
) => {
  const beforeFieldNames = beforeType.fields.map(field => field.name)
  const afterFieldNames = afterType.fields.map(field => field.name)
  const sharedFieldNames = beforeFieldNames.filter(fieldName => afterFieldNames.includes(fieldName))
  const appendedFieldNames = afterFieldNames.slice(sharedFieldNames.length)

  if (!isSubsequence(sharedFieldNames, afterFieldNames)) {
    warnings.add(`Composite ${beforeType.name} reorders existing attributes. Generate the composite type migration manually.`)
    return []
  }

  if (appendedFieldNames.some(fieldName => sharedFieldNames.includes(fieldName))) {
    warnings.add(`Composite ${beforeType.name} inserts new attributes before existing ones. Generate the composite type migration manually.`)
    return []
  }

  const beforeFields = new Map(beforeType.fields.map(field => [field.name, field] as const))
  const afterFields = new Map(afterType.fields.map(field => [field.name, field] as const))
  const statements: string[] = []

  beforeType.fields.forEach((field) => {
    if (!afterFields.has(field.name)) {
      statements.push(
        `ALTER TYPE ${formatQualifiedSqlName(beforeType.name)} DROP ATTRIBUTE IF EXISTS ${quoteSqlIdentifier(field.name)};`
      )
    }
  })

  sharedFieldNames.forEach((fieldName) => {
    const beforeField = beforeFields.get(fieldName) || null
    const afterField = afterFields.get(fieldName) || null

    if (!beforeField || !afterField || beforeField.type === afterField.type) {
      return
    }

    statements.push(
      `ALTER TYPE ${formatQualifiedSqlName(afterType.name)} ALTER ATTRIBUTE ${quoteSqlIdentifier(fieldName)} TYPE ${afterField.type};`
    )
  })

  appendedFieldNames.forEach((fieldName) => {
    const afterField = afterFields.get(fieldName) || null

    if (!afterField) {
      return
    }

    statements.push(
      `ALTER TYPE ${formatQualifiedSqlName(afterType.name)} ADD ATTRIBUTE ${quoteSqlIdentifier(afterField.name)} ${afterField.type};`
    )
  })

  return statements
}

const buildCustomTypeModificationStatements = (
  beforeType: PgmlCustomType,
  afterType: PgmlCustomType,
  warnings: Set<string>
) => {
  if (beforeType.kind !== afterType.kind) {
    warnings.add(`Type ${beforeType.name} changes kind from ${beforeType.kind} to ${afterType.kind}. Generate the type migration manually.`)
    return []
  }

  if (beforeType.kind === 'Enum' && afterType.kind === 'Enum') {
    return buildEnumAlterStatements(beforeType, afterType, warnings)
  }

  if (beforeType.kind === 'Composite' && afterType.kind === 'Composite') {
    return buildCompositeAlterStatements(beforeType, afterType, warnings)
  }

  warnings.add(`Domain ${beforeType.name} changed. Generate the domain migration manually because PGML cannot infer a safe ALTER DOMAIN sequence.`)

  return []
}

const buildRoutineCreateStatement = (kind: 'Function' | 'Procedure', routine: PgmlRoutine, warnings: Set<string>) => {
  if (!routine.source) {
    warnings.add(`${kind} ${routine.name} has no source block and was omitted from the migration diff.`)
    return null
  }

  return ensureSqlStatement(routine.source)
}

const parseRoutineDropSignature = (routine: PgmlRoutine) => {
  const normalizedSignature = routine.signature
    .replace(/\[[^\]]+\]\s*$/u, '')
    .replace(/\s+returns\s+.+$/iu, '')
    .trim()
  const signatureMatch = normalizedSignature.match(/^(.+?)\((.*)\)$/u)

  if (!signatureMatch) {
    return null
  }

  const routineName = (signatureMatch[1] || '').trim()
  const parameterList = (signatureMatch[2] || '').trim()
  const parameterTypes = parameterList.length === 0
    ? []
    : parameterList.split(',').map((entry) => {
        const normalizedEntry = entry
          .trim()
          .replace(/^(?:inout|in|out|variadic)\s+/iu, '')
        const parts = normalizedEntry.split(/\s+/u)

        if (parts.length <= 1) {
          return normalizedEntry
        }

        return parts.slice(1).join(' ')
      })

  if (routineName.length === 0 || parameterTypes.some(parameterType => parameterType.length === 0)) {
    return null
  }

  return {
    parameterTypes,
    routineName
  }
}

const buildRoutineDropStatement = (
  kind: 'Function' | 'Procedure',
  routine: PgmlRoutine,
  warnings: Set<string>
) => {
  const parsedSignature = parseRoutineDropSignature(routine)

  if (!parsedSignature) {
    warnings.add(`${kind} ${routine.name} was removed, but its signature could not be converted into DROP ${kind.toUpperCase()} SQL.`)
    return null
  }

  return `DROP ${kind.toUpperCase()} IF EXISTS ${formatQualifiedSqlName(parsedSignature.routineName)}(${parsedSignature.parameterTypes.join(', ')});`
}

const buildTriggerCreateStatement = (trigger: PgmlTrigger, warnings: Set<string>) => {
  if (!trigger.source) {
    warnings.add(`Trigger ${trigger.name} has no source block and was omitted from the migration diff.`)
    return null
  }

  return ensureSqlStatement(trigger.source)
}

const buildTriggerDropStatement = (trigger: PgmlTrigger) => {
  return `DROP TRIGGER IF EXISTS ${quoteSqlIdentifier(trigger.name)} ON ${formatQualifiedSqlName(trigger.tableName)};`
}

const buildConstraintCreateStatement = (tableId: string, constraint: PgmlConstraint) => {
  const normalizedExpression = constraint.expression.trim()

  if (/^(?:primary key|unique|foreign key|check)\b/i.test(normalizedExpression)) {
    return `ALTER TABLE ${formatQualifiedSqlName(tableId)} ADD CONSTRAINT ${quoteSqlIdentifier(constraint.name)} ${normalizedExpression};`
  }

  return `ALTER TABLE ${formatQualifiedSqlName(tableId)} ADD CONSTRAINT ${quoteSqlIdentifier(constraint.name)} CHECK (${constraint.expression});`
}

const buildConstraintDropStatement = (tableId: string, constraint: PgmlConstraint) => {
  return `ALTER TABLE ${formatQualifiedSqlName(tableId)} DROP CONSTRAINT IF EXISTS ${quoteSqlIdentifier(constraint.name)};`
}

const buildTableAlterStatements = (
  beforeTable: PgmlTable,
  afterTable: PgmlTable,
  warnings: Set<string>,
  normalizeType: (value: string) => string
): PgmlTableAlterPlan => {
  const preAlterStatements: string[] = []
  const tableStatements: string[] = []
  const postAlterStatements: string[] = []
  const beforeColumns = buildColumnMap(beforeTable)
  const afterColumns = buildColumnMap(afterTable)
  const columnNames = Array.from(new Set([...beforeColumns.keys(), ...afterColumns.keys()])).sort((left, right) => {
    return left.localeCompare(right)
  })

  const beforeIndexes = buildIndexMap(beforeTable)
  const afterIndexes = buildIndexMap(afterTable)
  const indexNames = Array.from(new Set([...beforeIndexes.keys(), ...afterIndexes.keys()])).sort((left, right) => left.localeCompare(right))

  indexNames.forEach((indexName) => {
    const beforeIndex = beforeIndexes.get(indexName) || null
    const afterIndex = afterIndexes.get(indexName) || null

    if (beforeIndex && !afterIndex) {
      preAlterStatements.push(`DROP INDEX IF EXISTS ${quoteSqlIdentifier(beforeIndex.name)};`)
      return
    }

    if (
      beforeIndex
      && afterIndex
      && toStableJson(normalizeIndexForCompare(beforeIndex)) !== toStableJson(normalizeIndexForCompare(afterIndex))
    ) {
      preAlterStatements.push(`DROP INDEX IF EXISTS ${quoteSqlIdentifier(beforeIndex.name)};`)
    }
  })

  const beforeConstraints = buildConstraintMap(beforeTable)
  const afterConstraints = buildConstraintMap(afterTable)
  const constraintNames = Array.from(new Set([...beforeConstraints.keys(), ...afterConstraints.keys()])).sort((left, right) => left.localeCompare(right))

  constraintNames.forEach((constraintName) => {
    const beforeConstraint = beforeConstraints.get(constraintName) || null
    const afterConstraint = afterConstraints.get(constraintName) || null

    if (beforeConstraint && !afterConstraint) {
      preAlterStatements.push(buildConstraintDropStatement(beforeTable.fullName, beforeConstraint))
      return
    }

    if (
      beforeConstraint
      && afterConstraint
      && toStableJson(normalizeConstraintForCompare(beforeConstraint)) !== toStableJson(normalizeConstraintForCompare(afterConstraint))
    ) {
      preAlterStatements.push(buildConstraintDropStatement(beforeTable.fullName, beforeConstraint))
    }
  })

  columnNames.forEach((columnName) => {
    const beforeColumn = beforeColumns.get(columnName) || null
    const afterColumn = afterColumns.get(columnName) || null

    if (!beforeColumn && afterColumn) {
      tableStatements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ADD COLUMN ${buildColumnDefinition(afterColumn)};`)
      return
    }

    if (beforeColumn && !afterColumn) {
      tableStatements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} DROP COLUMN IF EXISTS ${quoteSqlIdentifier(beforeColumn.name)};`)
      return
    }

    if (!beforeColumn || !afterColumn) {
      return
    }

    const normalizedBeforeColumn = normalizePgmlCompareColumnValue({
      column: beforeColumn,
      normalizeType,
      tableId: beforeTable.fullName
    })
    const normalizedAfterColumn = normalizePgmlCompareColumnValue({
      column: afterColumn,
      normalizeType,
      tableId: afterTable.fullName
    })

    if (normalizedBeforeColumn.type !== normalizedAfterColumn.type) {
      tableStatements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} TYPE ${afterColumn.type};`)
    }

    const beforeDefault = getNormalizedPgmlColumnDefaultModifierValue(normalizedBeforeColumn.modifiers)
    const afterDefault = getNormalizedPgmlColumnDefaultModifierValue(normalizedAfterColumn.modifiers)

    if (beforeDefault !== afterDefault) {
      if (afterDefault) {
        tableStatements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} SET DEFAULT ${afterDefault};`)
      } else {
        tableStatements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} DROP DEFAULT;`)
      }
    }

    const normalizedBeforeModifiers = normalizePgmlColumnModifiers(normalizedBeforeColumn.modifiers)
    const normalizedAfterModifiers = normalizePgmlColumnModifiers(normalizedAfterColumn.modifiers)
    const beforeNotNull = normalizedBeforeModifiers.includes('not null')
    const afterNotNull = normalizedAfterModifiers.includes('not null')

    if (beforeNotNull !== afterNotNull) {
      tableStatements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} ${afterNotNull ? 'SET' : 'DROP'} NOT NULL;`)
    }

    if (normalizedBeforeModifiers.includes('unique') !== normalizedAfterModifiers.includes('unique')) {
      warnings.add(`Column uniqueness changed for ${afterTable.fullName}.${afterColumn.name}; migration output does not infer named unique constraints automatically.`)
    }

    if (normalizedBeforeModifiers.includes('pk') !== normalizedAfterModifiers.includes('pk')) {
      warnings.add(`Primary key membership changed for ${afterTable.fullName}.${afterColumn.name}; migration output does not rewrite primary keys automatically.`)
    }
  })

  indexNames.forEach((indexName) => {
    const beforeIndex = beforeIndexes.get(indexName) || null
    const afterIndex = afterIndexes.get(indexName) || null

    if (!beforeIndex && afterIndex) {
      postAlterStatements.push(buildCreateIndexStatement(afterTable.fullName, afterIndex))
      return
    }

    if (
      beforeIndex
      && afterIndex
      && toStableJson(normalizeIndexForCompare(beforeIndex)) !== toStableJson(normalizeIndexForCompare(afterIndex))
    ) {
      postAlterStatements.push(buildCreateIndexStatement(afterTable.fullName, afterIndex))
    }
  })

  constraintNames.forEach((constraintName) => {
    const beforeConstraint = beforeConstraints.get(constraintName) || null
    const afterConstraint = afterConstraints.get(constraintName) || null

    if (!beforeConstraint && afterConstraint) {
      postAlterStatements.push(buildConstraintCreateStatement(afterTable.fullName, afterConstraint))
      return
    }

    if (
      beforeConstraint
      && afterConstraint
      && toStableJson(normalizeConstraintForCompare(beforeConstraint)) !== toStableJson(normalizeConstraintForCompare(afterConstraint))
    ) {
      postAlterStatements.push(buildConstraintCreateStatement(afterTable.fullName, afterConstraint))
    }
  })

  return {
    postAlterStatements,
    preAlterStatements,
    tableStatements
  }
}

const buildTableFingerprint = (table: PgmlTable) => {
  return table.columns
    .map(column => `${column.name}:${column.type}`)
    .sort((left, right) => left.localeCompare(right))
    .join('|')
}

const addRenameLikeTableWarnings = (
  beforeTables: Map<string, PgmlTable>,
  afterTables: Map<string, PgmlTable>,
  warnings: Set<string>
) => {
  const removedTables = Array.from(beforeTables.values()).filter(table => !afterTables.has(table.fullName))
  const addedTables = Array.from(afterTables.values()).filter(table => !beforeTables.has(table.fullName))

  removedTables.forEach((removedTable) => {
    const removedFingerprint = buildTableFingerprint(removedTable)
    const renameCandidate = addedTables.find((addedTable) => {
      return buildTableFingerprint(addedTable) === removedFingerprint
    })

    if (renameCandidate) {
      warnings.add(`Table ${removedTable.fullName} was removed while ${renameCandidate.fullName} was added with the same column signature; review for a possible rename that the migration emitted as DROP plus CREATE.`)
    }
  })
}

export const buildPgmlMigrationDiffPlan = (
  baseModel: PgmlSchemaModel,
  targetModel: PgmlSchemaModel
): PgmlMigrationDiffPlan => {
  const warnings = new Set<string>()
  const phases = createEmptyMigrationStatementPhases()
  const normalizeCompareTypeExpression = createPgmlCompareTypeExpressionNormalizer([
    baseModel,
    targetModel
  ])
  const beforeTypesByName = new Map(baseModel.customTypes.map((customType) => {
    return [normalizePgmlCompareCustomTypeName(customType.name, normalizeCompareTypeExpression), customType] as const
  }))
  const afterTypesByName = new Map(targetModel.customTypes.map((customType) => {
    return [normalizePgmlCompareCustomTypeName(customType.name, normalizeCompareTypeExpression), customType] as const
  }))
  const crossKindTypeNames = new Set(
    Array.from(new Set([...beforeTypesByName.keys(), ...afterTypesByName.keys()])).filter((typeName) => {
      const beforeType = beforeTypesByName.get(typeName) || null
      const afterType = afterTypesByName.get(typeName) || null

      return beforeType && afterType && beforeType.kind !== afterType.kind
    })
  )

  const beforeTypes = buildCustomTypeMap(baseModel.customTypes, normalizeCompareTypeExpression)
  const afterTypes = buildCustomTypeMap(targetModel.customTypes, normalizeCompareTypeExpression)
  const typeIds = Array.from(new Set([...beforeTypes.keys(), ...afterTypes.keys()])).sort((left, right) => left.localeCompare(right))

  typeIds.forEach((typeId) => {
    const beforeType = beforeTypes.get(typeId) || null
    const afterType = afterTypes.get(typeId) || null

    if ((beforeType && crossKindTypeNames.has(beforeType.name)) || (afterType && crossKindTypeNames.has(afterType.name))) {
      const typeName = beforeType?.name || afterType?.name || typeId

      warnings.add(`Type ${typeName} changes kind across versions. Generate the type migration manually.`)
      return
    }

    if (beforeType && !afterType) {
      phases.postDependencyCleanup.push(buildDropCustomTypeStatement(beforeType))
      return
    }

    if (!beforeType && afterType) {
      phases.preTablePreparations.push(buildCreateCustomTypeStatement(afterType))
      return
    }

    if (
      beforeType
      && afterType
      && toStableJson(normalizeCustomTypeForCompare(beforeType, normalizeCompareTypeExpression)) !== toStableJson(normalizeCustomTypeForCompare(afterType, normalizeCompareTypeExpression))
    ) {
      buildCustomTypeModificationStatements(beforeType, afterType, warnings).forEach((statement) => {
        phases.preTablePreparations.push(statement)
      })
    }
  })

  const beforeTables = buildTableMap(baseModel.tables)
  const afterTables = buildTableMap(targetModel.tables)
  const beforeSequences = buildSequenceMap(baseModel.sequences)
  const afterSequences = buildSequenceMap(targetModel.sequences)
  const sequenceIds = Array.from(new Set([...beforeSequences.keys(), ...afterSequences.keys()])).sort((left, right) => left.localeCompare(right))

  sequenceIds.forEach((sequenceId) => {
    const beforeSequence = beforeSequences.get(sequenceId) || null
    const afterSequence = afterSequences.get(sequenceId) || null

    if (beforeSequence && !afterSequence) {
      if (isImplicitSerialSequenceOnlyDiff({
        afterTables,
        beforeTables,
        normalizeType: normalizeCompareTypeExpression,
        sequence: beforeSequence,
        type: 'removed'
      })) {
        return
      }

      phases.postDependencyCleanup.push(buildDropSequenceStatement(beforeSequence))
      return
    }

    if (!beforeSequence && afterSequence) {
      if (isImplicitSerialSequenceOnlyDiff({
        afterTables,
        beforeTables,
        normalizeType: normalizeCompareTypeExpression,
        sequence: afterSequence,
        type: 'added'
      })) {
        return
      }

      phases.preTablePreparations.push(buildCreateSequenceStatement(afterSequence))
      return
    }

    if (
      beforeSequence
      && afterSequence
      && toStableJson(normalizeSequenceForCompare(beforeSequence, normalizeCompareTypeExpression)) !== toStableJson(normalizeSequenceForCompare(afterSequence, normalizeCompareTypeExpression))
    ) {
      warnings.add(`Sequence ${beforeSequence.name} changed. Generate the sequence migration manually because PGML cannot infer a safe ALTER SEQUENCE sequence from the stored source.`)
    }
  })
  addRenameLikeTableWarnings(beforeTables, afterTables, warnings)
  const tableIds = Array.from(new Set([...beforeTables.keys(), ...afterTables.keys()])).sort((left, right) => left.localeCompare(right))

  tableIds.forEach((tableId) => {
    const beforeTable = beforeTables.get(tableId) || null
    const afterTable = afterTables.get(tableId) || null

    if (beforeTable && !afterTable) {
      phases.tableStatements.push(`DROP TABLE IF EXISTS ${formatQualifiedSqlName(beforeTable.fullName)};`)
      return
    }

    if (!beforeTable && afterTable) {
      phases.tableStatements.push(buildCreateTableStatement(afterTable))
      afterTable.indexes.forEach((index) => {
        phases.tableStatements.push(buildCreateIndexStatement(afterTable.fullName, index))
      })
      return
    }

    if (beforeTable && afterTable) {
      const tableAlterPlan = buildTableAlterStatements(
        beforeTable,
        afterTable,
        warnings,
        normalizeCompareTypeExpression
      )

      tableAlterPlan.preAlterStatements.forEach(statement => phases.preDependencyDrops.push(statement))
      tableAlterPlan.tableStatements.forEach(statement => phases.tableStatements.push(statement))
      tableAlterPlan.postAlterStatements.forEach(statement => phases.postTableStatements.push(statement))
    }
  })

  const beforeReferences = buildReferenceMap(baseModel.references)
  const afterReferences = buildReferenceMap(targetModel.references)
  const referenceIds = Array.from(new Set([...beforeReferences.keys(), ...afterReferences.keys()])).sort((left, right) => left.localeCompare(right))

  referenceIds.forEach((referenceId) => {
    const beforeReference = beforeReferences.get(referenceId) || null
    const afterReference = afterReferences.get(referenceId) || null

    if (beforeReference && !afterReference) {
      phases.preDependencyDrops.push(buildDropReferenceStatement(beforeReference))
      return
    }

    if (!beforeReference && afterReference) {
      phases.postTableStatements.push(buildCreateReferenceStatement(afterReference))
      return
    }

    if (
      beforeReference
      && afterReference
      && toStableJson(normalizeReferenceForCompare(beforeReference)) !== toStableJson(normalizeReferenceForCompare(afterReference))
    ) {
      phases.preDependencyDrops.push(buildDropReferenceStatement(beforeReference))
      phases.postTableStatements.push(buildCreateReferenceStatement(afterReference))
    }
  })

  ;(['Function', 'Procedure'] as const).forEach((kind) => {
    const beforeRoutines = buildRoutineMap(kind === 'Function' ? baseModel.functions : baseModel.procedures)
    const afterRoutines = buildRoutineMap(kind === 'Function' ? targetModel.functions : targetModel.procedures)
    const routineIds = Array.from(new Set([...beforeRoutines.keys(), ...afterRoutines.keys()])).sort((left, right) => left.localeCompare(right))

    routineIds.forEach((routineId) => {
      const beforeRoutine = beforeRoutines.get(routineId) || null
      const afterRoutine = afterRoutines.get(routineId) || null

      if (beforeRoutine && !afterRoutine) {
        const dropStatement = buildRoutineDropStatement(kind, beforeRoutine, warnings)

        if (dropStatement) {
          phases.preDependencyDrops.push(dropStatement)
        }

        return
      }

      if (!afterRoutine) {
        return
      }

      if (
        !beforeRoutine
        || (() => {
          const normalizedPair = normalizePgmlCompareRoutinePairValues(beforeRoutine, afterRoutine)

          return toStableJson(normalizedPair.before) !== toStableJson(normalizedPair.after)
        })()
      ) {
        const statement = buildRoutineCreateStatement(kind, afterRoutine, warnings)

        if (statement) {
          phases.postTableStatements.push(statement)
        }
      }
    })
  })

  const beforeTriggers = new Map(
    baseModel.triggers.map(trigger => [`${normalizeTriggerTableKey(trigger.tableName)}::${trigger.name}`, trigger] as const)
  )
  const afterTriggers = new Map(
    targetModel.triggers.map(trigger => [`${normalizeTriggerTableKey(trigger.tableName)}::${trigger.name}`, trigger] as const)
  )
  const triggerIds = Array.from(new Set([...beforeTriggers.keys(), ...afterTriggers.keys()])).sort((left, right) => left.localeCompare(right))

  triggerIds.forEach((triggerId) => {
    const beforeTrigger = beforeTriggers.get(triggerId) || null
    const afterTrigger = afterTriggers.get(triggerId) || null

    if (beforeTrigger && !afterTrigger) {
      phases.preDependencyDrops.push(buildTriggerDropStatement(beforeTrigger))
      return
    }

    if (!afterTrigger) {
      return
    }

    if (
      !beforeTrigger
      || toStableJson(normalizeTriggerForCompare(beforeTrigger)) !== toStableJson(normalizeTriggerForCompare(afterTrigger))
    ) {
      if (beforeTrigger) {
        phases.preDependencyDrops.push(buildTriggerDropStatement(beforeTrigger))
      }

      const statement = buildTriggerCreateStatement(afterTrigger, warnings)

      if (statement) {
        phases.postTableStatements.push(statement)
      }
    }
  })

  return {
    statements: finalizeMigrationStatements(phases),
    warnings: Array.from(warnings).sort((left, right) => left.localeCompare(right))
  }
}

export const buildPgmlMigrationDiffBundle = (
  baseModel: PgmlSchemaModel,
  targetModel: PgmlSchemaModel,
  options: {
    baseName?: string
  } = {}
): PgmlMigrationDiffBundle => {
  const plan = buildPgmlMigrationDiffPlan(baseModel, targetModel)

  return buildPgmlMigrationArtifactsFromPlan(plan, options)
}
