import type { PgmlExportArtifact } from './pgml-export'
import type {
  PgmlConstraint,
  PgmlCustomType,
  PgmlIndex,
  PgmlReference,
  PgmlRoutine,
  PgmlSchemaModel,
  PgmlSequence,
  PgmlTable,
  PgmlTrigger
} from './pgml'

export type PgmlMigrationDiffBundle = {
  sql: {
    migration: PgmlExportArtifact
  }
}

const sqlHeader = '-- Generated by PGML version diff.'
const toStableJson = (value: unknown): string => {
  if (Array.isArray(value)) {
    return `[${value.map(entry => toStableJson(entry)).join(',')}]`
  }

  if (value && typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>)
      .filter(([, entry]) => entry !== undefined)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, entry]) => `"${key}":${toStableJson(entry)}`)

    return `{${entries.join(',')}}`
  }

  return JSON.stringify(value)
}
const normalizeExportBaseName = (value: string) => {
  const normalized = value
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '')

  return normalized.length > 0 ? normalized : 'pgml-version'
}

const splitQualifiedName = (value: string, defaultSchema = 'public') => {
  const parts = value
    .split('.')
    .map(entry => entry.trim())
    .filter(entry => entry.length > 0)

  if (parts.length <= 1) {
    return {
      name: parts[0] || value.trim(),
      schema: defaultSchema
    }
  }

  return {
    name: parts.at(-1) || value.trim(),
    schema: parts.slice(0, -1).join('.')
  }
}

const quoteSqlIdentifier = (value: string) => `"${value.replaceAll('"', '""')}"`

const formatQualifiedSqlName = (value: string, defaultSchema = 'public') => {
  const { name, schema } = splitQualifiedName(value, defaultSchema)

  return `${quoteSqlIdentifier(schema)}.${quoteSqlIdentifier(name)}`
}

const formatSqlIdentifierList = (values: string[]) => values.map(value => quoteSqlIdentifier(value)).join(', ')

const ensureSqlStatement = (value: string) => {
  const trimmed = value.trim()

  if (trimmed.length === 0) {
    return ''
  }

  return trimmed.endsWith(';') ? trimmed : `${trimmed};`
}

const buildReferenceActionClause = (keyword: 'DELETE' | 'UPDATE', action: string | null) => {
  if (!action || action.trim().length === 0) {
    return ''
  }

  return ` ON ${keyword} ${action.trim().toUpperCase()}`
}

const getColumnDefaultValue = (column: PgmlColumn) => {
  return column.modifiers.find(modifier => modifier.startsWith('default:'))?.replace('default:', '').trim() || null
}

const buildColumnDefinition = (column: PgmlColumn) => {
  const columnParts = [`${quoteSqlIdentifier(column.name)} ${column.type}`]

  if (column.modifiers.includes('not null')) {
    columnParts.push('NOT NULL')
  }

  if (column.modifiers.includes('unique')) {
    columnParts.push('UNIQUE')
  }

  if (column.modifiers.includes('pk')) {
    columnParts.push('PRIMARY KEY')
  }

  const defaultValue = getColumnDefaultValue(column)

  if (defaultValue) {
    columnParts.push(`DEFAULT ${defaultValue}`)
  }

  return columnParts.join(' ')
}

const buildCreateTableStatement = (table: PgmlTable) => {
  const primaryKeyColumns = table.columns
    .filter(column => column.modifiers.includes('pk'))
    .map(column => column.name)
  const lines = table.columns.map((column) => {
    const columnParts = [`${quoteSqlIdentifier(column.name)} ${column.type}`]

    if (column.modifiers.includes('not null')) {
      columnParts.push('NOT NULL')
    }

    if (column.modifiers.includes('unique')) {
      columnParts.push('UNIQUE')
    }

    const defaultValue = getColumnDefaultValue(column)

    if (defaultValue) {
      columnParts.push(`DEFAULT ${defaultValue}`)
    }

    if (primaryKeyColumns.length === 1 && column.modifiers.includes('pk')) {
      columnParts.push('PRIMARY KEY')
    }

    return `  ${columnParts.join(' ')}`
  })

  if (primaryKeyColumns.length > 1) {
    lines.push(`  PRIMARY KEY (${formatSqlIdentifierList(primaryKeyColumns)})`)
  }

  table.constraints.forEach((constraint) => {
    const normalizedExpression = constraint.expression.trim()

    if (/^(?:primary key|unique|foreign key|check)\b/i.test(normalizedExpression)) {
      lines.push(`  CONSTRAINT ${quoteSqlIdentifier(constraint.name)} ${normalizedExpression}`)
      return
    }

    lines.push(`  CONSTRAINT ${quoteSqlIdentifier(constraint.name)} CHECK (${constraint.expression})`)
  })

  return `CREATE TABLE ${formatQualifiedSqlName(table.fullName)} (\n${lines.join(',\n')}\n);`
}

const buildCreateIndexStatement = (tableId: string, index: PgmlIndex) => {
  return `CREATE INDEX ${quoteSqlIdentifier(index.name)} ON ${formatQualifiedSqlName(tableId)} USING ${index.type || 'btree'} (${formatSqlIdentifierList(index.columns)});`
}

const buildCreateReferenceStatement = (reference: PgmlReference) => {
  return `ALTER TABLE ${formatQualifiedSqlName(reference.fromTable)} ADD FOREIGN KEY (${quoteSqlIdentifier(reference.fromColumn)}) REFERENCES ${formatQualifiedSqlName(reference.toTable)} (${quoteSqlIdentifier(reference.toColumn)})${buildReferenceActionClause('DELETE', reference.onDelete)}${buildReferenceActionClause('UPDATE', reference.onUpdate)};`
}

const buildDropReferenceStatement = (reference: PgmlReference) => {
  const { name: tableName } = splitQualifiedName(reference.fromTable)
  const constraintName = `${tableName}_${reference.fromColumn}_fkey`

  return `ALTER TABLE ${formatQualifiedSqlName(reference.fromTable)} DROP CONSTRAINT IF EXISTS ${quoteSqlIdentifier(constraintName)};`
}

const buildCreateCustomTypeStatement = (customType: PgmlCustomType) => {
  if (customType.kind === 'Enum') {
    return `CREATE TYPE ${formatQualifiedSqlName(customType.name)} AS ENUM (${customType.values.map(value => `'${value.replaceAll('\'', '\'\'')}'`).join(', ')});`
  }

  if (customType.kind === 'Domain') {
    const parts = [`CREATE DOMAIN ${formatQualifiedSqlName(customType.name)} AS ${customType.baseType || 'text'}`]

    if (customType.check) {
      parts.push(`CHECK (${customType.check})`)
    }

    return `${parts.join(' ')};`
  }

  return `CREATE TYPE ${formatQualifiedSqlName(customType.name)} AS (\n${customType.fields.map(field => `  ${quoteSqlIdentifier(field.name)} ${field.type}`).join(',\n')}\n);`
}

const buildDropCustomTypeStatement = (customType: PgmlCustomType) => {
  if (customType.kind === 'Domain') {
    return `DROP DOMAIN IF EXISTS ${formatQualifiedSqlName(customType.name)};`
  }

  return `DROP TYPE IF EXISTS ${formatQualifiedSqlName(customType.name)};`
}

const buildCreateSequenceStatement = (sequence: PgmlSequence) => {
  if (sequence.source) {
    return ensureSqlStatement(sequence.source)
  }

  return `CREATE SEQUENCE ${formatQualifiedSqlName(sequence.name)};`
}

const buildDropSequenceStatement = (sequence: PgmlSequence) => {
  return `DROP SEQUENCE IF EXISTS ${formatQualifiedSqlName(sequence.name)};`
}

const buildRoutineMap = (routines: PgmlRoutine[]) => {
  return new Map(routines.map(routine => [routine.name, routine] as const))
}

const buildSequenceMap = (sequences: PgmlSequence[]) => {
  return new Map(sequences.map(sequence => [sequence.name, sequence] as const))
}

const buildCustomTypeMap = (customTypes: PgmlCustomType[]) => {
  return new Map(customTypes.map(customType => [`${customType.kind}::${customType.name}`, customType] as const))
}

const buildTableMap = (tables: PgmlTable[]) => {
  return new Map(tables.map(table => [table.fullName, table] as const))
}

const buildReferenceMap = (references: PgmlReference[]) => {
  return new Map(references.map(reference => [[
    reference.fromTable,
    reference.fromColumn,
    reference.relation,
    reference.toTable,
    reference.toColumn
  ].join('::'), reference] as const))
}

const buildIndexMap = (table: PgmlTable) => {
  return new Map(table.indexes.map(index => [index.name, index] as const))
}

const buildConstraintMap = (table: PgmlTable) => {
  return new Map(table.constraints.map(constraint => [constraint.name, constraint] as const))
}

const buildColumnMap = (table: PgmlTable) => {
  return new Map(table.columns.map(column => [column.name, column] as const))
}

const normalizeMetadataEntries = (
  entries: Array<{
    key: string
    value: string
  }>
) => {
  return [...entries].sort((left, right) => {
    if (left.key !== right.key) {
      return left.key.localeCompare(right.key)
    }

    return left.value.localeCompare(right.value)
  })
}

const normalizeDocumentationValue = (
  documentation: PgmlRoutine['docs'] | PgmlTrigger['docs'] | PgmlSequence['docs']
) => {
  if (!documentation) {
    return null
  }

  return {
    entries: [...documentation.entries].sort((left, right) => {
      if (left.key !== right.key) {
        return left.key.localeCompare(right.key)
      }

      return left.value.localeCompare(right.value)
    }),
    summary: documentation.summary
  }
}

const normalizeAffectsValue = (affects: PgmlRoutine['affects'] | PgmlTrigger['affects'] | PgmlSequence['affects']) => {
  if (!affects) {
    return null
  }

  return {
    calls: [...affects.calls].sort((left, right) => left.localeCompare(right)),
    dependsOn: [...affects.dependsOn].sort((left, right) => left.localeCompare(right)),
    extras: [...affects.extras].map((entry) => {
      return {
        key: entry.key,
        values: [...entry.values].sort((left, right) => left.localeCompare(right))
      }
    }).sort((left, right) => left.key.localeCompare(right.key)),
    ownedBy: [...affects.ownedBy].sort((left, right) => left.localeCompare(right)),
    reads: [...affects.reads].sort((left, right) => left.localeCompare(right)),
    sets: [...affects.sets].sort((left, right) => left.localeCompare(right)),
    uses: [...affects.uses].sort((left, right) => left.localeCompare(right)),
    writes: [...affects.writes].sort((left, right) => left.localeCompare(right))
  }
}

const normalizeIndexForCompare = (index: PgmlIndex) => {
  return {
    columns: index.columns,
    name: index.name,
    type: index.type
  }
}

const normalizeConstraintForCompare = (constraint: PgmlConstraint) => {
  return {
    expression: constraint.expression,
    name: constraint.name
  }
}

const normalizeReferenceForCompare = (reference: PgmlReference) => {
  return {
    fromColumn: reference.fromColumn,
    fromTable: reference.fromTable,
    onDelete: reference.onDelete,
    onUpdate: reference.onUpdate,
    relation: reference.relation,
    toColumn: reference.toColumn,
    toTable: reference.toTable
  }
}

const normalizeRoutineForCompare = (routine: PgmlRoutine) => {
  return {
    affects: normalizeAffectsValue(routine.affects),
    docs: normalizeDocumentationValue(routine.docs),
    metadata: normalizeMetadataEntries(routine.metadata),
    name: routine.name,
    signature: routine.signature,
    source: routine.source?.trim() || null
  }
}

const normalizeTriggerForCompare = (trigger: PgmlTrigger) => {
  return {
    affects: normalizeAffectsValue(trigger.affects),
    docs: normalizeDocumentationValue(trigger.docs),
    metadata: normalizeMetadataEntries(trigger.metadata),
    name: trigger.name,
    source: trigger.source?.trim() || null,
    tableName: trigger.tableName
  }
}

const normalizeSequenceForCompare = (sequence: PgmlSequence) => {
  return {
    affects: normalizeAffectsValue(sequence.affects),
    docs: normalizeDocumentationValue(sequence.docs),
    metadata: normalizeMetadataEntries(sequence.metadata),
    name: sequence.name,
    source: sequence.source?.trim() || null
  }
}

const normalizeCustomTypeForCompare = (customType: PgmlCustomType) => {
  if (customType.kind === 'Enum') {
    return {
      kind: customType.kind,
      name: customType.name,
      values: customType.values
    }
  }

  if (customType.kind === 'Domain') {
    return {
      baseType: customType.baseType,
      check: customType.check,
      kind: customType.kind,
      name: customType.name
    }
  }

  return {
    fields: customType.fields,
    kind: customType.kind,
    name: customType.name
  }
}

const buildRoutineCreateStatement = (kind: 'Function' | 'Procedure', routine: PgmlRoutine, warnings: Set<string>) => {
  if (!routine.source) {
    warnings.add(`${kind} ${routine.name} has no source block and was omitted from the migration diff.`)
    return null
  }

  return ensureSqlStatement(routine.source)
}

const buildTriggerCreateStatement = (trigger: PgmlTrigger, warnings: Set<string>) => {
  if (!trigger.source) {
    warnings.add(`Trigger ${trigger.name} has no source block and was omitted from the migration diff.`)
    return null
  }

  return ensureSqlStatement(trigger.source)
}

const buildTriggerDropStatement = (trigger: PgmlTrigger) => {
  return `DROP TRIGGER IF EXISTS ${quoteSqlIdentifier(trigger.name)} ON ${formatQualifiedSqlName(trigger.tableName)};`
}

const buildConstraintCreateStatement = (tableId: string, constraint: PgmlConstraint) => {
  const normalizedExpression = constraint.expression.trim()

  if (/^(?:primary key|unique|foreign key|check)\b/i.test(normalizedExpression)) {
    return `ALTER TABLE ${formatQualifiedSqlName(tableId)} ADD CONSTRAINT ${quoteSqlIdentifier(constraint.name)} ${normalizedExpression};`
  }

  return `ALTER TABLE ${formatQualifiedSqlName(tableId)} ADD CONSTRAINT ${quoteSqlIdentifier(constraint.name)} CHECK (${constraint.expression});`
}

const buildConstraintDropStatement = (tableId: string, constraint: PgmlConstraint) => {
  return `ALTER TABLE ${formatQualifiedSqlName(tableId)} DROP CONSTRAINT IF EXISTS ${quoteSqlIdentifier(constraint.name)};`
}

const buildTableAlterStatements = (
  beforeTable: PgmlTable,
  afterTable: PgmlTable,
  warnings: Set<string>
) => {
  const statements: string[] = []
  const beforeColumns = buildColumnMap(beforeTable)
  const afterColumns = buildColumnMap(afterTable)
  const columnNames = Array.from(new Set([...beforeColumns.keys(), ...afterColumns.keys()])).sort((left, right) => {
    return left.localeCompare(right)
  })

  columnNames.forEach((columnName) => {
    const beforeColumn = beforeColumns.get(columnName) || null
    const afterColumn = afterColumns.get(columnName) || null

    if (!beforeColumn && afterColumn) {
      statements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ADD COLUMN ${buildColumnDefinition(afterColumn)};`)
      return
    }

    if (beforeColumn && !afterColumn) {
      statements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} DROP COLUMN IF EXISTS ${quoteSqlIdentifier(beforeColumn.name)};`)
      return
    }

    if (!beforeColumn || !afterColumn) {
      return
    }

    if (beforeColumn.type !== afterColumn.type) {
      statements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} TYPE ${afterColumn.type};`)
    }

    const beforeDefault = getColumnDefaultValue(beforeColumn)
    const afterDefault = getColumnDefaultValue(afterColumn)

    if (beforeDefault !== afterDefault) {
      if (afterDefault) {
        statements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} SET DEFAULT ${afterDefault};`)
      } else {
        statements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} DROP DEFAULT;`)
      }
    }

    const beforeNotNull = beforeColumn.modifiers.includes('not null')
    const afterNotNull = afterColumn.modifiers.includes('not null')

    if (beforeNotNull !== afterNotNull) {
      statements.push(`ALTER TABLE ${formatQualifiedSqlName(afterTable.fullName)} ALTER COLUMN ${quoteSqlIdentifier(afterColumn.name)} ${afterNotNull ? 'SET' : 'DROP'} NOT NULL;`)
    }

    if (beforeColumn.modifiers.includes('unique') !== afterColumn.modifiers.includes('unique')) {
      warnings.add(`Column uniqueness changed for ${afterTable.fullName}.${afterColumn.name}; migration output does not infer named unique constraints automatically.`)
    }

    if (beforeColumn.modifiers.includes('pk') !== afterColumn.modifiers.includes('pk')) {
      warnings.add(`Primary key membership changed for ${afterTable.fullName}.${afterColumn.name}; migration output does not rewrite primary keys automatically.`)
    }
  })

  const beforeIndexes = buildIndexMap(beforeTable)
  const afterIndexes = buildIndexMap(afterTable)
  const indexNames = Array.from(new Set([...beforeIndexes.keys(), ...afterIndexes.keys()])).sort((left, right) => left.localeCompare(right))

  indexNames.forEach((indexName) => {
    const beforeIndex = beforeIndexes.get(indexName) || null
    const afterIndex = afterIndexes.get(indexName) || null

    if (!beforeIndex && afterIndex) {
      statements.push(buildCreateIndexStatement(afterTable.fullName, afterIndex))
      return
    }

    if (beforeIndex && !afterIndex) {
      statements.push(`DROP INDEX IF EXISTS ${quoteSqlIdentifier(beforeIndex.name)};`)
      return
    }

    if (
      beforeIndex
      && afterIndex
      && toStableJson(normalizeIndexForCompare(beforeIndex)) !== toStableJson(normalizeIndexForCompare(afterIndex))
    ) {
      statements.push(`DROP INDEX IF EXISTS ${quoteSqlIdentifier(beforeIndex.name)};`)
      statements.push(buildCreateIndexStatement(afterTable.fullName, afterIndex))
    }
  })

  const beforeConstraints = buildConstraintMap(beforeTable)
  const afterConstraints = buildConstraintMap(afterTable)
  const constraintNames = Array.from(new Set([...beforeConstraints.keys(), ...afterConstraints.keys()])).sort((left, right) => left.localeCompare(right))

  constraintNames.forEach((constraintName) => {
    const beforeConstraint = beforeConstraints.get(constraintName) || null
    const afterConstraint = afterConstraints.get(constraintName) || null

    if (!beforeConstraint && afterConstraint) {
      statements.push(buildConstraintCreateStatement(afterTable.fullName, afterConstraint))
      return
    }

    if (beforeConstraint && !afterConstraint) {
      statements.push(buildConstraintDropStatement(afterTable.fullName, beforeConstraint))
      return
    }

    if (
      beforeConstraint
      && afterConstraint
      && toStableJson(normalizeConstraintForCompare(beforeConstraint)) !== toStableJson(normalizeConstraintForCompare(afterConstraint))
    ) {
      statements.push(buildConstraintDropStatement(afterTable.fullName, beforeConstraint))
      statements.push(buildConstraintCreateStatement(afterTable.fullName, afterConstraint))
    }
  })

  return statements
}

export const buildPgmlMigrationDiffBundle = (
  baseModel: PgmlSchemaModel,
  targetModel: PgmlSchemaModel,
  options: {
    baseName?: string
  } = {}
): PgmlMigrationDiffBundle => {
  const warnings = new Set<string>()
  const statements: string[] = []
  const baseName = normalizeExportBaseName(options.baseName || 'pgml-version')

  const beforeTypes = buildCustomTypeMap(baseModel.customTypes)
  const afterTypes = buildCustomTypeMap(targetModel.customTypes)
  const typeIds = Array.from(new Set([...beforeTypes.keys(), ...afterTypes.keys()])).sort((left, right) => left.localeCompare(right))

  typeIds.forEach((typeId) => {
    const beforeType = beforeTypes.get(typeId) || null
    const afterType = afterTypes.get(typeId) || null

    if (beforeType && !afterType) {
      statements.push(buildDropCustomTypeStatement(beforeType))
      return
    }

    if (!beforeType && afterType) {
      statements.push(buildCreateCustomTypeStatement(afterType))
      return
    }

    if (
      beforeType
      && afterType
      && toStableJson(normalizeCustomTypeForCompare(beforeType)) !== toStableJson(normalizeCustomTypeForCompare(afterType))
    ) {
      statements.push(buildDropCustomTypeStatement(beforeType))
      statements.push(buildCreateCustomTypeStatement(afterType))
    }
  })

  const beforeSequences = buildSequenceMap(baseModel.sequences)
  const afterSequences = buildSequenceMap(targetModel.sequences)
  const sequenceIds = Array.from(new Set([...beforeSequences.keys(), ...afterSequences.keys()])).sort((left, right) => left.localeCompare(right))

  sequenceIds.forEach((sequenceId) => {
    const beforeSequence = beforeSequences.get(sequenceId) || null
    const afterSequence = afterSequences.get(sequenceId) || null

    if (beforeSequence && !afterSequence) {
      statements.push(buildDropSequenceStatement(beforeSequence))
      return
    }

    if (!beforeSequence && afterSequence) {
      statements.push(buildCreateSequenceStatement(afterSequence))
      return
    }

    if (
      beforeSequence
      && afterSequence
      && toStableJson(normalizeSequenceForCompare(beforeSequence)) !== toStableJson(normalizeSequenceForCompare(afterSequence))
    ) {
      statements.push(buildDropSequenceStatement(beforeSequence))
      statements.push(buildCreateSequenceStatement(afterSequence))
    }
  })

  const beforeTables = buildTableMap(baseModel.tables)
  const afterTables = buildTableMap(targetModel.tables)
  const tableIds = Array.from(new Set([...beforeTables.keys(), ...afterTables.keys()])).sort((left, right) => left.localeCompare(right))

  tableIds.forEach((tableId) => {
    const beforeTable = beforeTables.get(tableId) || null
    const afterTable = afterTables.get(tableId) || null

    if (beforeTable && !afterTable) {
      statements.push(`DROP TABLE IF EXISTS ${formatQualifiedSqlName(beforeTable.fullName)};`)
      return
    }

    if (!beforeTable && afterTable) {
      statements.push(buildCreateTableStatement(afterTable))
      afterTable.indexes.forEach((index) => {
        statements.push(buildCreateIndexStatement(afterTable.fullName, index))
      })
      return
    }

    if (beforeTable && afterTable) {
      buildTableAlterStatements(beforeTable, afterTable, warnings).forEach(statement => statements.push(statement))
    }
  })

  const beforeReferences = buildReferenceMap(baseModel.references)
  const afterReferences = buildReferenceMap(targetModel.references)
  const referenceIds = Array.from(new Set([...beforeReferences.keys(), ...afterReferences.keys()])).sort((left, right) => left.localeCompare(right))

  referenceIds.forEach((referenceId) => {
    const beforeReference = beforeReferences.get(referenceId) || null
    const afterReference = afterReferences.get(referenceId) || null

    if (beforeReference && !afterReference) {
      statements.push(buildDropReferenceStatement(beforeReference))
      return
    }

    if (!beforeReference && afterReference) {
      statements.push(buildCreateReferenceStatement(afterReference))
      return
    }

    if (
      beforeReference
      && afterReference
      && toStableJson(normalizeReferenceForCompare(beforeReference)) !== toStableJson(normalizeReferenceForCompare(afterReference))
    ) {
      statements.push(buildDropReferenceStatement(beforeReference))
      statements.push(buildCreateReferenceStatement(afterReference))
    }
  })

  ;(['Function', 'Procedure'] as const).forEach((kind) => {
    const beforeRoutines = buildRoutineMap(kind === 'Function' ? baseModel.functions : baseModel.procedures)
    const afterRoutines = buildRoutineMap(kind === 'Function' ? targetModel.functions : targetModel.procedures)
    const routineIds = Array.from(new Set([...beforeRoutines.keys(), ...afterRoutines.keys()])).sort((left, right) => left.localeCompare(right))

    routineIds.forEach((routineId) => {
      const beforeRoutine = beforeRoutines.get(routineId) || null
      const afterRoutine = afterRoutines.get(routineId) || null

      if (beforeRoutine && !afterRoutine) {
        warnings.add(`${kind} ${beforeRoutine.name} was removed; the diff migration does not emit DROP ${kind.toUpperCase()} automatically.`)
        return
      }

      if (!afterRoutine) {
        return
      }

      if (
        !beforeRoutine
        || toStableJson(normalizeRoutineForCompare(beforeRoutine)) !== toStableJson(normalizeRoutineForCompare(afterRoutine))
      ) {
        const statement = buildRoutineCreateStatement(kind, afterRoutine, warnings)

        if (statement) {
          statements.push(statement)
        }
      }
    })
  })

  const beforeTriggers = new Map(baseModel.triggers.map(trigger => [`${trigger.tableName}::${trigger.name}`, trigger] as const))
  const afterTriggers = new Map(targetModel.triggers.map(trigger => [`${trigger.tableName}::${trigger.name}`, trigger] as const))
  const triggerIds = Array.from(new Set([...beforeTriggers.keys(), ...afterTriggers.keys()])).sort((left, right) => left.localeCompare(right))

  triggerIds.forEach((triggerId) => {
    const beforeTrigger = beforeTriggers.get(triggerId) || null
    const afterTrigger = afterTriggers.get(triggerId) || null

    if (beforeTrigger && !afterTrigger) {
      statements.push(buildTriggerDropStatement(beforeTrigger))
      return
    }

    if (!afterTrigger) {
      return
    }

    if (
      !beforeTrigger
      || toStableJson(normalizeTriggerForCompare(beforeTrigger)) !== toStableJson(normalizeTriggerForCompare(afterTrigger))
    ) {
      if (beforeTrigger) {
        statements.push(buildTriggerDropStatement(beforeTrigger))
      }

      const statement = buildTriggerCreateStatement(afterTrigger, warnings)

      if (statement) {
        statements.push(statement)
      }
    }
  })

  return {
    sql: {
      migration: {
        content: `${sqlHeader}\n\nBEGIN;\n\n${statements.join('\n\n')}\n\nCOMMIT;\n`,
        fileName: `${baseName}.migration.sql`,
        label: 'Version Migration SQL',
        warnings: Array.from(warnings)
      }
    }
  }
}
