import {
  getPgmlVersionById,
  getPgmlVersionDisplayLabel,
  getPgmlVersionLineage,
  isPgmlVersionAncestor,
  type PgmlVersionSetDocument
} from './pgml-document'
import { parsePgml } from './pgml'
import {
  buildPgmlMigrationArtifactsFromPlan,
  buildPgmlMigrationDiffPlan,
  type PgmlMigrationDiffBundle,
  type PgmlMigrationDiffPlan
} from './pgml-migration-diff'

type PgmlVersionMigrationTargetId = 'workspace' | string

type PgmlResolvedVersionMigrationStep = {
  baseId: string
  baseLabel: string
  baseSource: string
  targetId: PgmlVersionMigrationTargetId
  targetLabel: string
  targetSource: string
}

type PgmlPlannedVersionMigrationStep = {
  index: number
  label: string
  plan: PgmlMigrationDiffPlan
}

type PgmlVersionMigrationValidation = {
  isValid: boolean
  issues: string[]
}

export type PgmlVersionMigrationStepBundle = PgmlMigrationDiffBundle & {
  index: number
  label: string
  target: {
    baseId: string
    baseLabel: string
    targetId: PgmlVersionMigrationTargetId
    targetLabel: string
  }
  validation: PgmlVersionMigrationValidation
}

export type PgmlVersionMigrationBundle = PgmlMigrationDiffBundle & {
  meta: PgmlMigrationDiffBundle['meta'] & {
    historyAware: boolean
    stepCount: number
    validation: PgmlVersionMigrationValidation
  }
  steps: PgmlVersionMigrationStepBundle[]
}

const workspaceTargetLabel = 'Current workspace'
const versionHistorySqlHeader = '-- Generated by PGML version history diff.'
const versionHistoryKyselyHeader = '// Generated by PGML version history diff.'

const normalizeBaseName = (value: string) => {
  const normalized = value
    .trim()
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/g, '-')
    .replaceAll(/^-+|-+$/g, '')

  return normalized.length > 0 ? normalized : 'pgml-version'
}

const escapeTemplateLiteralContent = (value: string) => {
  return value
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${')
}

const buildStepBaseName = (
  baseName: string,
  stepIndex: number,
  step: PgmlResolvedVersionMigrationStep
) => {
  const normalizedTargetLabel = normalizeBaseName(`${step.baseLabel}-to-${step.targetLabel}`)

  return `${baseName}.step-${stepIndex + 1}-${normalizedTargetLabel}`
}

const buildVersionHistorySqlContent = (steps: PgmlPlannedVersionMigrationStep[]) => {
  const sections = steps.map((step) => {
    const warningLines = step.plan.warnings.map(warning => `-- Warning: ${warning}`)
    const statementLines = step.plan.statements.length > 0
      ? step.plan.statements
      : ['-- No automatic SQL statements were generated for this step. Review warnings.']

    return `-- Step ${step.index + 1}: ${step.label}\n${[...warningLines, ...statementLines].join('\n\n')}`
  })

  return `${versionHistorySqlHeader}\n\nBEGIN;\n\n${sections.join('\n\n')}\n\nCOMMIT;\n`
}

const buildVersionHistoryKyselyContent = (
  baseName: string,
  steps: PgmlPlannedVersionMigrationStep[]
) => {
  const stepBlocks = steps
    .map((step) => {
      const warningLines = step.plan.warnings.map(warning => `  // Warning: ${warning}`)
      const statements = step.plan.statements.map((statement) => {
        return `  await sql\`
${escapeTemplateLiteralContent(statement)}
\`.execute(db)`
      }).join('\n\n')
      const body = statements.length > 0
        ? statements
        : '  // No automatic SQL statements were generated for this step. Review warnings.'

      return `  // Step ${step.index + 1}: ${step.label}\n${[...warningLines, body].join('\n')}`
    })
    .join('\n\n')

  return `${versionHistoryKyselyHeader}
import type { Kysely } from 'kysely'
import { sql } from 'kysely'
import type { Database } from './${baseName}.database'

export const up = async (db: Kysely<Database>): Promise<void> => {
${stepBlocks}
}

export const down = async (): Promise<void> => {
  throw new Error('PGML exports generate forward-only migrations. Write the down migration manually.')
}
`
}

const validateOrderedContentSnippets = (
  content: string,
  snippets: string[]
) => {
  let searchIndex = 0

  for (const snippet of snippets) {
    if (snippet.trim().length === 0) {
      continue
    }

    const snippetIndex = content.indexOf(snippet, searchIndex)

    if (snippetIndex < 0) {
      return false
    }

    searchIndex = snippetIndex + snippet.length
  }

  return true
}

const createMigrationValidation = (
  issues: string[]
) => {
  return {
    isValid: issues.length === 0,
    issues
  } satisfies PgmlVersionMigrationValidation
}

const validateMigrationWarnings = (
  actualWarnings: string[],
  expectedWarnings: string[],
  message: string
) => {
  // History-aware exports need warning parity as much as statement parity.
  // A "successful" step file is still misleading if it silently drops the
  // manual follow-up notes that PGML diffing surfaced for that transition.
  const normalizedActual = JSON.stringify(actualWarnings)
  const normalizedExpected = JSON.stringify(expectedWarnings)

  if (normalizedActual === normalizedExpected) {
    return []
  }

  return [message]
}

const validateStepMigrationArtifacts = (input: {
  index: number
  label: string
  plan: PgmlMigrationDiffPlan
  stepBundle: PgmlMigrationDiffBundle
}) => {
  // Validate the persisted artifact content against the underlying PGML diff
  // plan so each generated file continues to represent exactly one version
  // transition in the expected order.
  const issues: string[] = []
  const expectedSqlSnippets = input.plan.statements
  const expectedKyselySnippets = input.plan.statements.map(statement => escapeTemplateLiteralContent(statement))

  if (
    !validateOrderedContentSnippets(
      input.stepBundle.sql.migration.content,
      expectedSqlSnippets
    )
  ) {
    issues.push(`SQL step ${input.index + 1} does not contain the expected statements for ${input.label}.`)
  }

  if (
    !validateOrderedContentSnippets(
      input.stepBundle.kysely.migration.content,
      expectedKyselySnippets
    )
  ) {
    issues.push(`Kysely step ${input.index + 1} does not contain the expected statements for ${input.label}.`)
  }

  issues.push(...validateMigrationWarnings(
    input.stepBundle.sql.migration.warnings,
    input.plan.warnings,
    `SQL step ${input.index + 1} does not report the expected warnings for ${input.label}.`
  ))
  issues.push(...validateMigrationWarnings(
    input.stepBundle.kysely.migration.warnings,
    input.plan.warnings,
    `Kysely step ${input.index + 1} does not report the expected warnings for ${input.label}.`
  ))

  return createMigrationValidation(issues)
}

const validateCombinedHistoryArtifacts = (input: {
  combinedArtifacts: ReturnType<typeof buildCombinedHistoryArtifacts>
  stepDescriptors: PgmlPlannedVersionMigrationStep[]
}) => {
  // Combined history exports are intentionally synthesized from the ordered
  // step descriptors. The validation keeps the aggregate view honest by
  // proving the rendered file preserves that same lineage sequence.
  const issues: string[] = []
  const expectedSqlSnippets = input.stepDescriptors.flatMap((step) => {
    return [
      `-- Step ${step.index + 1}: ${step.label}`,
      ...step.plan.warnings.map(warning => `-- Warning: ${warning}`),
      ...(step.plan.statements.length > 0
        ? step.plan.statements
        : ['-- No automatic SQL statements were generated for this step. Review warnings.'])
    ]
  })
  const expectedKyselySnippets = input.stepDescriptors.flatMap((step) => {
    return [
      `  // Step ${step.index + 1}: ${step.label}`,
      ...step.plan.warnings.map(warning => `  // Warning: ${warning}`),
      ...(step.plan.statements.length > 0
        ? step.plan.statements.map(statement => escapeTemplateLiteralContent(statement))
        : ['  // No automatic SQL statements were generated for this step. Review warnings.'])
    ]
  })

  if (!validateOrderedContentSnippets(input.combinedArtifacts.sql.content, expectedSqlSnippets)) {
    issues.push('Combined SQL history migration does not match the expected PGML version sequence.')
  }

  if (!validateOrderedContentSnippets(input.combinedArtifacts.kysely.content, expectedKyselySnippets)) {
    issues.push('Combined Kysely history migration does not match the expected PGML version sequence.')
  }

  return createMigrationValidation(issues)
}

const validateFallbackMigrationArtifacts = (
  artifactBundle: PgmlMigrationDiffBundle,
  plan: PgmlMigrationDiffPlan
) => {
  const issues: string[] = []

  if (!validateOrderedContentSnippets(artifactBundle.sql.migration.content, plan.statements)) {
    issues.push('Fallback SQL migration does not match the expected PGML diff output.')
  }

  if (
    !validateOrderedContentSnippets(
      artifactBundle.kysely.migration.content,
      plan.statements.map(statement => escapeTemplateLiteralContent(statement))
    )
  ) {
    issues.push('Fallback Kysely migration does not match the expected PGML diff output.')
  }

  issues.push(...validateMigrationWarnings(
    artifactBundle.sql.migration.warnings,
    plan.warnings,
    'Fallback SQL migration warnings do not match the expected PGML diff output.'
  ))
  issues.push(...validateMigrationWarnings(
    artifactBundle.kysely.migration.warnings,
    plan.warnings,
    'Fallback Kysely migration warnings do not match the expected PGML diff output.'
  ))

  return createMigrationValidation(issues)
}

const prefixStepWarnings = (
  warnings: string[],
  label: string
) => {
  return warnings.map(warning => `${label}: ${warning}`)
}

const buildMigrationStepLabel = (step: {
  baseLabel: string
  targetLabel: string
}) => {
  return `${step.baseLabel} -> ${step.targetLabel}`
}

const buildPlannedStepDescriptors = (steps: Array<{
  plan: PgmlMigrationDiffPlan
  target: {
    baseLabel: string
    targetLabel: string
  }
}>): PgmlPlannedVersionMigrationStep[] => {
  return steps.map((step, index) => {
    return {
      index,
      label: `${step.target.baseLabel} -> ${step.target.targetLabel}`,
      plan: step.plan
    }
  })
}

const buildResolvedVersionMigrationSteps = (
  document: PgmlVersionSetDocument,
  baseVersionId: string | null,
  targetId: PgmlVersionMigrationTargetId
) => {
  // History-aware migrations only make sense when the selected base/target pair
  // follows a forward lineage through locked checkpoints.
  if (!baseVersionId) {
    return null
  }

  if (targetId === 'workspace') {
    const workspaceBaseId = document.workspace.basedOnVersionId

    if (!workspaceBaseId) {
      return null
    }

    if (baseVersionId === workspaceBaseId) {
      const baseVersion = getPgmlVersionById(document, baseVersionId)

      if (!baseVersion) {
        return null
      }

      return [{
        baseId: baseVersion.id,
        baseLabel: getPgmlVersionDisplayLabel(baseVersion),
        baseSource: baseVersion.snapshot.source,
        targetId,
        targetLabel: workspaceTargetLabel,
        targetSource: document.workspace.snapshot.source
      }] satisfies PgmlResolvedVersionMigrationStep[]
    }

    if (!isPgmlVersionAncestor(document, baseVersionId, workspaceBaseId)) {
      return null
    }

    const workspaceBaseVersion = getPgmlVersionById(document, workspaceBaseId)

    if (!workspaceBaseVersion) {
      return null
    }

    const lineage = getPgmlVersionLineage(document, workspaceBaseId)
    const startIndex = lineage.findIndex(version => version.id === baseVersionId)

    if (startIndex === -1) {
      return null
    }

    const resolvedSteps: PgmlResolvedVersionMigrationStep[] = []

    for (let index = startIndex; index < lineage.length - 1; index += 1) {
      const baseVersion = lineage[index]!
      const targetVersion = lineage[index + 1]!

      resolvedSteps.push({
        baseId: baseVersion.id,
        baseLabel: getPgmlVersionDisplayLabel(baseVersion),
        baseSource: baseVersion.snapshot.source,
        targetId: targetVersion.id,
        targetLabel: getPgmlVersionDisplayLabel(targetVersion),
        targetSource: targetVersion.snapshot.source
      })
    }

    resolvedSteps.push({
      baseId: workspaceBaseVersion.id,
      baseLabel: getPgmlVersionDisplayLabel(workspaceBaseVersion),
      baseSource: workspaceBaseVersion.snapshot.source,
      targetId,
      targetLabel: workspaceTargetLabel,
      targetSource: document.workspace.snapshot.source
    })

    return resolvedSteps
  }

  const targetVersion = getPgmlVersionById(document, targetId)

  if (!targetVersion) {
    return null
  }

  if (baseVersionId === targetVersion.id) {
    return []
  }

  if (!isPgmlVersionAncestor(document, baseVersionId, targetVersion.id)) {
    return null
  }

  const lineage = getPgmlVersionLineage(document, targetVersion.id)
  const startIndex = lineage.findIndex(version => version.id === baseVersionId)

  if (startIndex === -1) {
    return null
  }

  const resolvedSteps: PgmlResolvedVersionMigrationStep[] = []

  for (let index = startIndex; index < lineage.length - 1; index += 1) {
    const baseVersion = lineage[index]!
    const nextVersion = lineage[index + 1]!

    resolvedSteps.push({
      baseId: baseVersion.id,
      baseLabel: getPgmlVersionDisplayLabel(baseVersion),
      baseSource: baseVersion.snapshot.source,
      targetId: nextVersion.id,
      targetLabel: getPgmlVersionDisplayLabel(nextVersion),
      targetSource: nextVersion.snapshot.source
    })
  }

  return resolvedSteps
}

const buildFallbackMigrationWarnings = (
  planWarnings: string[],
  input: {
    hasSelectedBase: boolean
    historyWarning?: string | null
  }
) => {
  const warnings = [...planWarnings]

  if (!input.hasSelectedBase) {
    warnings.unshift('No base version is selected. The migration is being generated from an empty schema.')
  }

  if (input.historyWarning) {
    warnings.unshift(input.historyWarning)
  }

  return warnings
}

const buildCombinedHistoryArtifacts = (
  normalizedBaseName: string,
  prefixedWarnings: string[],
  stepDescriptors: PgmlPlannedVersionMigrationStep[]
) => {
  return {
    kysely: {
      content: buildVersionHistoryKyselyContent(normalizedBaseName, stepDescriptors),
      fileName: `${normalizedBaseName}.migration.ts`,
      label: 'Version Migration',
      warnings: prefixedWarnings
    },
    sql: {
      content: buildVersionHistorySqlContent(stepDescriptors),
      fileName: `${normalizedBaseName}.migration.sql`,
      label: 'Version Migration SQL',
      warnings: prefixedWarnings
    }
  }
}

const buildFallbackVersionMigrationBundle = (
  input: {
    baseSource: string
    hasSelectedBase: boolean
    targetSource: string
  },
  options: {
    baseName?: string
    historyWarning?: string | null
  } = {}
): PgmlVersionMigrationBundle => {
  // When the compare pair is not a simple forward lineage, the app falls back
  // to the aggregate diff so users still get a usable forward migration. The
  // fallback remains validated so regression tests catch mismatches here too.
  const plan = buildPgmlMigrationDiffPlan(
    parsePgml(input.baseSource),
    parsePgml(input.targetSource)
  )
  const warnings = buildFallbackMigrationWarnings(plan.warnings, {
    hasSelectedBase: input.hasSelectedBase,
    historyWarning: options.historyWarning
  })

  const artifactBundle = buildPgmlMigrationArtifactsFromPlan({
    statements: plan.statements,
    warnings
  }, options)
  const validation = validateFallbackMigrationArtifacts(artifactBundle, {
    statements: plan.statements,
    warnings
  })

  return {
    ...artifactBundle,
    meta: {
      ...artifactBundle.meta,
      historyAware: false,
      stepCount: artifactBundle.meta.hasChanges ? 1 : 0,
      validation
    },
    steps: artifactBundle.meta.hasChanges
      ? [{
          ...artifactBundle,
          index: 0,
          label: 'Selected base -> Selected target',
          target: {
            baseId: input.hasSelectedBase ? 'selected-base' : 'empty',
            baseLabel: input.hasSelectedBase ? 'Selected base' : 'Empty schema',
            targetId: 'workspace',
            targetLabel: 'Selected target'
          },
          validation
        }]
      : []
  }
}

export const buildPgmlVersionMigrationBundle = (
  input: {
    baseSource: string
    baseVersionId?: string | null
    document?: PgmlVersionSetDocument | null
    hasSelectedBase: boolean
    targetId?: PgmlVersionMigrationTargetId
    targetSource: string
  },
  options: {
    baseName?: string
  } = {}
): PgmlVersionMigrationBundle => {
  const normalizedBaseName = normalizeBaseName(options.baseName || 'pgml-version')
  const resolvedSteps = input.document && input.hasSelectedBase
    ? buildResolvedVersionMigrationSteps(
        input.document,
        input.baseVersionId || null,
        input.targetId || 'workspace'
      )
    : null

  if (!resolvedSteps) {
    return buildFallbackVersionMigrationBundle(input, {
      ...options,
      historyWarning: input.hasSelectedBase
        ? 'Selected compare pair is not a forward version lineage. The migration was generated from the aggregate diff instead of per-version history.'
        : null
    })
  }

  // Each resolved step represents one predecessor -> successor transition in
  // the chosen version lineage. The UI can then expose those as individual
  // SQL/Kysely files while the combined artifact remains available for review.
  const stepBundles = resolvedSteps.map((step, stepIndex) => {
    const plan = buildPgmlMigrationDiffPlan(
      parsePgml(step.baseSource),
      parsePgml(step.targetSource)
    )

    const artifactBundle = buildPgmlMigrationArtifactsFromPlan(plan, {
      baseName: buildStepBaseName(normalizedBaseName, stepIndex, step)
    })
    const label = buildMigrationStepLabel({
      baseLabel: step.baseLabel,
      targetLabel: step.targetLabel
    })
    const validation = validateStepMigrationArtifacts({
      index: stepIndex,
      label,
      plan,
      stepBundle: artifactBundle
    })

    return {
      ...artifactBundle,
      index: stepIndex,
      label,
      plan,
      target: {
        baseId: step.baseId,
        baseLabel: step.baseLabel,
        targetId: step.targetId,
        targetLabel: step.targetLabel
      },
      validation
    }
  }).filter(step => step.meta.hasChanges || step.meta.warningCount > 0)
  const stepDescriptors = buildPlannedStepDescriptors(stepBundles)

  const prefixedWarnings = stepBundles.flatMap((step, stepIndex) => {
    return prefixStepWarnings(
      step.sql.migration.warnings,
      `Step ${stepIndex + 1} (${buildMigrationStepLabel(step.target)})`
    )
  })
  const combinedStatements = stepBundles.flatMap(step => step.plan.statements)
  const combinedArtifacts = buildCombinedHistoryArtifacts(
    normalizedBaseName,
    prefixedWarnings,
    stepDescriptors
  )
  const combinedValidation = createMigrationValidation([
    ...stepBundles.flatMap(step => step.validation.issues),
    ...validateCombinedHistoryArtifacts({
      combinedArtifacts,
      stepDescriptors
    }).issues
  ])

  return {
    kysely: {
      migration: combinedArtifacts.kysely
    },
    meta: {
      hasChanges: combinedStatements.length > 0,
      historyAware: true,
      statementCount: combinedStatements.length,
      stepCount: stepBundles.length,
      validation: combinedValidation,
      warningCount: prefixedWarnings.length
    },
    sql: {
      migration: combinedArtifacts.sql
    },
    steps: stepBundles.map((step) => {
      const { plan: _plan, ...bundle } = step

      return bundle
    })
  }
}
