import { readFileSync } from 'node:fs'

import { describe, expect, it } from 'vitest'

describe('Shared button theming source', () => {
  it('defines shared non-canvas button utilities with explicit focus treatment', () => {
    const file = readFileSync('/home/omar/Code/pgml/app/assets/css/main.css', 'utf8')

    expect(file).toContain('.studio-button {')
    expect(file).toContain('.studio-button:hover,')
    expect(file).toContain('.studio-button:focus-visible')
    expect(file).toContain('.studio-button--ghost')
    expect(file).toContain('.studio-choice-button')
    expect(file).toContain('.studio-toggle-chip')
  })

  it('uses the shared button classes in the app shell and diagram page controls', () => {
    const appFile = readFileSync('/home/omar/Code/pgml/app/app.vue', 'utf8')
    const canvasFile = readFileSync('/home/omar/Code/pgml/app/components/pgml/PgmlDiagramCanvas.vue', 'utf8')
    const tableRowsFile = readFileSync('/home/omar/Code/pgml/app/components/pgml/PgmlDiagramTableRows.vue', 'utf8')
    const diagramFile = readFileSync('/home/omar/Code/pgml/app/pages/diagram.vue', 'utf8')
    const indexFile = readFileSync('/home/omar/Code/pgml/app/pages/index.vue', 'utf8')
    const modalFrameFile = readFileSync('/home/omar/Code/pgml/app/components/studio/StudioModalFrame.vue', 'utf8')
    const studioUiFile = readFileSync('/home/omar/Code/pgml/app/composables/useStudioUi.ts', 'utf8')

    expect(appFile).toContain('headerMenuButtonClass')
    expect(appFile).toContain('title="Open header menu"')
    expect(appFile).toContain('@click="toggleStudioTheme"')
    expect(indexFile).toContain(':class="buttonClasses.secondary"')
    expect(indexFile).toContain(':class="buttonClasses.ghost"')
    expect(studioUiFile).toContain('const studioButtonClasses = Object.freeze({')
    expect(studioUiFile).toContain('const getStudioChoiceButtonClass = ({')
    expect(studioUiFile).toContain('const getStudioToggleChipClass = ({')
    expect(studioUiFile).toContain('studioModalUi: {')
    expect(studioUiFile).toContain('export const useStudioUi = () => studioUi')
    expect(modalFrameFile).toContain('<UModal')
    expect(modalFrameFile).toContain('buttonClasses.iconGhost')
    expect(modalFrameFile).toContain('studioModalUi')
    expect(diagramFile).toContain('} = useStudioUi()')
    expect(diagramFile).toContain('<StudioModalFrame')
    expect(diagramFile).toContain('const secondaryModalButtonClass = buttonClasses.secondary')
    expect(diagramFile).toContain('const primaryModalButtonClass = buttonClasses.primary')
    expect(diagramFile).toContain('const editorVisibilityButtonClass = joinStudioClasses(')
    expect(diagramFile).toContain('getStudioChoiceButtonClass({')
    expect(diagramFile).toContain('getStudioToggleChipClass({')
    expect(canvasFile).toContain('const sidePanelCloseButtonClass = joinStudioClasses(')
    expect(canvasFile).toContain('getStudioStateButtonClass({')
    expect(canvasFile).toContain('getStudioTabButtonClass(')
    expect(canvasFile).toContain('studioSelectUi')
    expect(canvasFile).toContain('<PgmlDiagramTableRows')
    expect(tableRowsFile).toContain('columnModifierBadgeClass')
    expect(canvasFile).toContain('label="Add table"')
    expect(canvasFile).toContain('label="Add group"')
    expect(canvasFile).toContain(':label="isSidePanelOpen ? \'Hide panel\' : \'Show panel\'"')
  })
})
