import { describe, expect, it } from 'vitest'
import { readSourceFile, sourceFileExists } from './source-test-utils'

describe('Shared button theming source', () => {
  it('defines shared non-canvas button utilities with explicit focus treatment', () => {
    const file = readSourceFile('app/assets/css/main.css')

    expect(file).toContain('.studio-button {')
    expect(file).toContain('.studio-button:hover,')
    expect(file).toContain('.studio-button:focus-visible')
    expect(file).toContain('.studio-button--ghost')
    expect(file).toContain('.studio-choice-button')
    expect(file).toContain('.studio-toggle-chip')
  })

  it('uses the shared button classes in the app shell and diagram page controls', () => {
    const appFile = readSourceFile('app/app.vue')
    const defaultLayoutFile = readSourceFile('app/layouts/default.vue')
    const studioLayoutFile = readSourceFile('app/layouts/studio.vue')
    const themeToggleFile = readSourceFile('app/components/app/AppThemeToggleButton.vue')
    const mobileMenuFile = readSourceFile('app/components/app/AppMobileNavigationMenu.vue')
    const desktopWorkspaceFile = readSourceFile('app/components/studio/StudioDesktopWorkspace.vue')
    const mobileWorkspaceFile = readSourceFile('app/components/studio/StudioMobileWorkspace.vue')
    const editorSurfaceFile = readSourceFile('app/components/studio/StudioEditorSurface.vue')
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const tableRowsFile = readSourceFile('app/components/pgml/PgmlDiagramTableRows.vue')
    const diagramFile = readSourceFile('app/pages/diagram.vue')
    const indexFile = readSourceFile('app/pages/index.vue')
    const sourceLaunchCardFile = readSourceFile('app/components/app/AppSourceLaunchCard.vue')
    const specFile = readSourceFile('app/pages/spec.vue')
    const modalFrameFile = readSourceFile('app/components/studio/StudioModalFrame.vue')
    const uiStylesFile = readSourceFile('app/utils/uiStyles.ts')
    const uiConstantsFile = readSourceFile('app/constants/ui.ts')

    expect(appFile).toContain('<NuxtLayout>')
    expect(defaultLayoutFile).toContain('<AppThemeToggleButton />')
    expect(studioLayoutFile).toContain('<AppThemeToggleButton />')
    expect(mobileMenuFile).toContain('title="Open header menu"')
    expect(themeToggleFile).toContain('@click="toggleStudioTheme"')
    expect(indexFile).toContain('<AppSourceLaunchCard')
    expect(indexFile).toContain('const specBannerButtonClass = studioButtonClasses.ghost')
    expect(indexFile).toContain('data-spec-banner="true"')
    expect(indexFile).toContain('label="Jump to spec"')
    expect(sourceLaunchCardFile).toContain('const itemActionButtonClass = joinStudioClasses(')
    expect(sourceLaunchCardFile).toContain('studioButtonClasses.iconGhost')
    expect(sourceLaunchCardFile).toContain('self-center')
    expect(specFile).toContain(':class="primaryCtaButtonClass"')
    expect(specFile).toContain(':class="secondaryCtaButtonClass"')
    expect(uiStylesFile).toContain('export const studioButtonClasses = Object.freeze({')
    expect(uiStylesFile).toContain('export const getStudioChoiceButtonClass = ({')
    expect(uiStylesFile).toContain('export const getStudioToggleChipClass = ({')
    expect(uiConstantsFile).toContain('export const studioModalUi')
    expect(uiConstantsFile).toContain('export const studioSelectUi')
    expect(modalFrameFile).toContain('<UModal')
    expect(modalFrameFile).toContain('studioButtonClasses.iconGhost')
    expect(modalFrameFile).toContain('studioModalUi')
    expect(diagramFile).not.toContain('useStudioUi')
    expect(diagramFile).toContain('<StudioModalFrame')
    expect(diagramFile).toContain('<StudioDesktopWorkspace')
    expect(diagramFile).toContain('<StudioMobileWorkspace')
    expect(diagramFile).toContain('<StudioEditorSurface')
    expect(diagramFile).toContain('const secondaryModalButtonClass = studioButtonClasses.secondary')
    expect(diagramFile).toContain('const primaryModalButtonClass = studioButtonClasses.primary')
    expect(desktopWorkspaceFile).toContain('const editorVisibilityButtonClass = joinStudioClasses(')
    expect(desktopWorkspaceFile).toContain('data-editor-visibility-toggle="true"')
    expect(editorSurfaceFile).toContain('data-pgml-diagnostics="true"')
    expect(editorSurfaceFile).toContain('data-document-scope-select="true"')
    expect(editorSurfaceFile).toContain('studioSelectUi')
    expect(editorSurfaceFile).toContain('showDocumentScopeSelect')
    expect(mobileWorkspaceFile).toContain('data-mobile-studio-menu="true"')
    expect(diagramFile).toContain('getStudioChoiceButtonClass({')
    expect(diagramFile).toContain('getStudioToggleChipClass({')
    expect(canvasFile).toContain('const sidePanelCloseButtonClass = joinStudioClasses(')
    expect(canvasFile).toContain('getStudioStateButtonClass({')
    expect(canvasFile).toContain('getStudioTabButtonClass(')
    expect(canvasFile).toContain('studioSelectUi')
    expect(tableRowsFile).toContain('columnModifierBadgeClass')
    expect(canvasFile).toContain('label="Add table"')
    expect(canvasFile).toContain('label="Add group"')
    expect(canvasFile).toContain(':label="isDiagramPanelVisible ? \'Hide panel\' : \'Show panel\'"')
    expect(sourceFileExists('app/composables/useStudioUi.ts')).toBe(false)
  })
})
