import { describe, expect, it } from 'vitest'
import { readSourceFile, sourceFileExists } from './source-test-utils'

describe('Shared button theming source', () => {
  it('defines shared non-canvas button utilities with explicit focus treatment', () => {
    const file = readSourceFile('app/assets/css/main.css')

    expect(file).toContain('.studio-button {')
    expect(file).toContain('.studio-button:hover,')
    expect(file).toContain('.studio-button:focus-visible')
    expect(file).toContain('.studio-button--ghost')
    expect(file).toContain('.studio-choice-button')
    expect(file).toContain('.studio-toggle-chip')
  })

  it('uses the shared button classes in the app shell and diagram page controls', () => {
    const appFile = readSourceFile('app/app.vue')
    const appHeaderFile = readSourceFile('app/components/AppHeader.vue')
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvas.vue')
    const tableRowsFile = readSourceFile('app/components/pgml/PgmlDiagramTableRows.vue')
    const diagramFile = readSourceFile('app/pages/diagram.vue')
    const indexFile = readSourceFile('app/pages/index.vue')
    const modalFrameFile = readSourceFile('app/components/studio/StudioModalFrame.vue')
    const uiStylesFile = readSourceFile('app/utils/uiStyles.ts')
    const uiConstantsFile = readSourceFile('app/constants/ui.ts')

    expect(appFile).toContain('<AppHeader>')
    expect(appHeaderFile).toContain('title="Open header menu"')
    expect(appHeaderFile).toContain('@click="toggleStudioTheme"')
    expect(indexFile).toContain(':class="primaryCtaButtonClass"')
    expect(indexFile).toContain(':class="secondaryCtaButtonClass"')
    expect(uiStylesFile).toContain('export const studioButtonClasses = Object.freeze({')
    expect(uiStylesFile).toContain('export const getStudioChoiceButtonClass = ({')
    expect(uiStylesFile).toContain('export const getStudioToggleChipClass = ({')
    expect(uiConstantsFile).toContain('export const studioModalUi')
    expect(uiConstantsFile).toContain('export const studioSelectUi')
    expect(modalFrameFile).toContain('<UModal')
    expect(modalFrameFile).toContain('studioButtonClasses.iconGhost')
    expect(modalFrameFile).toContain('studioModalUi')
    expect(diagramFile).not.toContain('useStudioUi')
    expect(diagramFile).toContain('<StudioModalFrame')
    expect(diagramFile).toContain('const secondaryModalButtonClass = studioButtonClasses.secondary')
    expect(diagramFile).toContain('const primaryModalButtonClass = studioButtonClasses.primary')
    expect(diagramFile).toContain('const editorVisibilityButtonClass = joinStudioClasses(')
    expect(diagramFile).toContain('getStudioChoiceButtonClass({')
    expect(diagramFile).toContain('getStudioToggleChipClass({')
    expect(canvasFile).toContain('const sidePanelCloseButtonClass = joinStudioClasses(')
    expect(canvasFile).toContain('getStudioStateButtonClass({')
    expect(canvasFile).toContain('getStudioTabButtonClass(')
    expect(canvasFile).toContain('studioSelectUi')
    expect(canvasFile).toContain('<PgmlDiagramTableRows')
    expect(tableRowsFile).toContain('columnModifierBadgeClass')
    expect(canvasFile).toContain('label="Add table"')
    expect(canvasFile).toContain('label="Add group"')
    expect(canvasFile).toContain(':label="isSidePanelOpen ? \'Hide panel\' : \'Show panel\'"')
    expect(sourceFileExists('app/composables/useStudioUi.ts')).toBe(false)
  })
})
