import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('diagram compare panel source', () => {
  it('renders a dedicated compare inspector and syncs it with the diagram shell', () => {
    const shellFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const comparePanelFile = readSourceFile('app/components/pgml/PgmlDiagramComparePanel.vue')
    const migrationsPanelFile = readSourceFile('app/components/pgml/PgmlDiagramMigrationsPanel.vue')
    const versionsPanelFile = readSourceFile('app/components/pgml/PgmlDiagramVersionsPanel.vue')

    expect(shellFile).toContain('const selectedCompareEntryId: Ref<string | null> = ref(null)')
    expect(shellFile).toContain('const isCompareDiagramActive = computed(() => {')
    expect(shellFile).toContain('const compareGhostOverlays = computed<DiagramCompareGhostOverlay[]>(() => {')
    expect(shellFile).toContain('const selectedDiagramCompareEntryIds = computed(() => {')
    expect(shellFile).toContain('const openComparator = () => {')
    expect(shellFile).toContain('data-diagram-tool-toggle="compare"')
    expect(shellFile).toContain('data-diagram-tool-toggle="migrations"')
    expect(shellFile).toContain('data-diagram-tool-toggle="versions"')
    expect(shellFile).toContain('data-diagram-tool-panel="true"')
    expect(shellFile).toContain('data-diagram-tool-panel-tab="compare"')
    expect(shellFile).toContain('data-diagram-tool-panel-tab="migrations"')
    expect(shellFile).toContain('data-diagram-tool-panel-tab="versions"')
    expect(shellFile).toContain('grid grid-cols-3 border-b border-[color:var(--studio-divider)]')
    expect(shellFile).toContain('<PgmlDiagramComparePanel')
    expect(shellFile).toContain(':compare-base-id="versionCompareBaseId"')
    expect(shellFile).toContain(':compare-options="versionCompareOptions"')
    expect(shellFile).toContain(':compare-target-id="versionCompareTargetId"')
    expect(shellFile).toContain(':excluded-group-names="compareExcludedGroupNames"')
    expect(shellFile).toContain(':excluded-table-ids="compareExcludedTableIds"')
    expect(shellFile).toContain('@edit-target-exclusions="emit(\'editCompareTargetExclusions\')"')
    expect(shellFile).toContain('@update:compare-base-id="emit(\'updateVersionCompareBaseId\', $event)"')
    expect(shellFile).toContain('@update:compare-target-id="emit(\'updateVersionCompareTargetId\', $event)"')
    expect(shellFile).toContain('<PgmlDiagramMigrationsPanel')
    expect(shellFile).toContain('<PgmlDiagramVersionsPanel')
    expect(shellFile).toContain('data-compare-ghost-entry="overlay.entryId"')

    expect(comparePanelFile).toContain('data-diagram-compare-panel="true"')
    expect(comparePanelFile).toContain('class="flex h-full min-h-0 min-w-0 flex-col overflow-hidden"')
    expect(comparePanelFile).toContain('data-studio-scrollable="true"')
    expect(comparePanelFile).toContain('data-compare-base-select="true"')
    expect(comparePanelFile).toContain('data-compare-target-select="true"')
    expect(comparePanelFile).toContain('data-compare-search="true"')
    expect(comparePanelFile).toContain('data-compare-edit-exclusions="true"')
    expect(comparePanelFile).toContain('data-compare-stat-filter="statKind"')
    expect(comparePanelFile).toContain('const compareStatLabelClass = \'font-mono text-[0.58rem] uppercase tracking-[0.08em]\'')
    expect(comparePanelFile).toContain('const exclusionChipClass = \'border border-[color:var(--studio-divider)] px-1.5 py-0.5 font-mono text-[0.52rem] uppercase tracking-[0.08em] text-[color:var(--studio-shell-muted)]\'')
    expect(comparePanelFile).toContain('data-compare-entry="entry.id"')
    expect(comparePanelFile).toContain('data-compare-entry-detail="true"')
    expect(comparePanelFile).toContain('type PgmlCompareFilterKind = \'all\' | \'added\' | \'modified\' | \'removed\'')
    expect(comparePanelFile).toContain('const compareStatKinds: PgmlCompareStatKind[] = [\'added\', \'modified\', \'removed\']')
    expect(comparePanelFile).toContain('const compareFilterOptions: PgmlCompareFilterOption[] = [')
    expect(comparePanelFile).toContain('const hasExcludedEntities = computed(() => {')
    expect(comparePanelFile).toContain('const toggleCompareStatFilter = (kind: PgmlCompareStatKind) => {')
    expect(comparePanelFile).toContain('const updateCompareBaseId = (value: unknown) => {')
    expect(comparePanelFile).toContain('const updateCompareTargetId = (value: unknown) => {')
    expect(comparePanelFile).toContain('[overflow-wrap:anywhere]')
    expect(comparePanelFile).toContain('v-for="option in compareFilterOptions"')
    expect(comparePanelFile).toContain('@click="toggleCompareStatFilter(statKind)"')
    expect(comparePanelFile).toContain('@click="emit(\'edit-target-exclusions\')"')
    expect(comparePanelFile).toContain('@click="clearFilters"')
    expect(comparePanelFile).toContain('label="Show on diagram"')
    expect(comparePanelFile).toContain('selectedDiagramContextIds')

    expect(migrationsPanelFile).toContain('data-diagram-migrations-panel="true"')
    expect(migrationsPanelFile).toContain('data-version-migration-format="sql"')
    expect(migrationsPanelFile).toContain('data-version-migration-download="activeMigrationFormat"')

    expect(versionsPanelFile).toContain('data-diagram-versions-panel="true"')
    expect(versionsPanelFile).toContain('Version Switcher')
    expect(versionsPanelFile).toContain(':data-version-view="version.id"')
    expect(versionsPanelFile).toContain(':data-version-restore="version.id"')
    expect(versionsPanelFile).not.toContain('data-version-open-comparator="true"')
    expect(versionsPanelFile).not.toContain('data-version-open-migrations="true"')
    expect(versionsPanelFile).not.toContain(':data-version-compare-base="version.id"')
    expect(versionsPanelFile).not.toContain(':data-version-compare-target="version.id"')
  })
})
