import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('studio mobile workspace source', () => {
  it('keeps the mobile studio shell and touch-aware canvas flow explicit in source', () => {
    const pageFile = readSourceFile('app/pages/diagram.vue')
    const mobileWorkspaceFile = readSourceFile('app/components/studio/StudioMobileWorkspace.vue')
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const connectionCanvasFile = readSourceFile('app/components/pgml/PgmlDiagramConnectionCanvas.vue')

    expect(pageFile).toContain('handleCanvasFocusSource')
    expect(pageFile).toContain('mobileWorkspaceView.value = \'pgml\'')
    expect(pageFile).toContain('const mobileToolPanelTab: Ref<DiagramToolPanelTab> = ref(\'versions\')')
    expect(pageFile).toContain(':mobile-active-view="mobileCanvasView"')
    expect(pageFile).toContain(':mobile-panel-tab="mobilePanelTab"')
    expect(pageFile).toContain(':mobile-tool-panel-tab="mobileToolPanelTab"')
    expect(pageFile).toContain('@tool-panel-tab-change="handleCanvasToolPanelTabChange"')
    expect(pageFile).toContain('@mobile-canvas-view-change="handleMobileCanvasViewChange"')
    expect(mobileWorkspaceFile).toContain('data-mobile-studio-menu="true"')
    expect(mobileWorkspaceFile).toContain('data-mobile-studio-current-view="true"')
    expect(mobileWorkspaceFile).toContain('const activeToolPanelTab = defineModel<DiagramToolPanelTab>(\'activeToolPanelTab\'')
    expect(mobileWorkspaceFile).toContain('key: \'tool-panel\'')
    expect(mobileWorkspaceFile).toContain('studioMobileWorkspaceViewLabelByValue[\'tool-panel\']')
    expect(mobileWorkspaceFile).toContain('diagramToolPanelTabLabelByValue')
    expect(mobileWorkspaceFile).toContain('children: [[')
    expect(canvasFile).toContain('const isMobileCanvasShell = computed(() => mobileActiveView !== null)')
    expect(canvasFile).toContain('const isMobilePanelView = computed(() => mobileActiveView === \'panel\')')
    expect(canvasFile).toContain('const isMobileToolPanelView = computed(() => mobileActiveView === \'tool-panel\')')
    expect(canvasFile).toContain('const shouldRenderSvgConnectionOverlay: Ref<boolean> = ref(false)')
    expect(canvasFile).toContain('const shouldPreferMainThreadConnectionRouting: Ref<boolean> = ref(false)')
    expect(canvasFile).toContain('const isAndroidBrowser = /Android/i.test(navigator.userAgent)')
    expect(canvasFile).toContain('shouldRenderAutomationPlane.value = !forceGpuScene && (')
    expect(canvasFile).toContain('shouldRenderSvgConnectionOverlay.value = !isAndroidBrowser && !shouldRenderAutomationPlane.value && prefersCoarsePointer')
    expect(canvasFile).toContain('shouldPreferMainThreadConnectionRouting.value = prefersCoarsePointer || isAndroidBrowser')
    expect(canvasFile).toContain('const svgConnectionOverlayTransform = computed(() => {')
    expect(canvasFile).toContain('const shouldShowToolPanel = computed(() => {')
    expect(canvasFile).toContain('emit(\'toolPanelTabChange\', tab)')
    expect(canvasFile).toContain('emit(\'mobileCanvasViewChange\', \'tool-panel\')')
    expect(canvasFile).toContain('emit(\'panelTabChange\', nextTab)')
    expect(canvasFile).toContain('panelTabChange')
    expect(canvasFile).toContain('toolPanelTabChange')
    expect(canvasFile).toContain('mobileActiveView')
    expect(canvasFile).toContain('v-else-if="shouldRenderSvgConnectionOverlay"')
    expect(canvasFile).toContain('<PgmlDiagramConnectionCanvas')
    expect(connectionCanvasFile).toContain('const getStrokeDasharray = (line: DiagramConnectionRenderLine) => {')
    expect(connectionCanvasFile).toContain('if (dashPattern.length === 0 || dashPattern === \'0\') {')
    expect(connectionCanvasFile).toContain('contentTransform = null')
    expect(connectionCanvasFile).toContain('renderHeight = null')
    expect(connectionCanvasFile).toContain('renderWidth = null')
    expect(connectionCanvasFile).toContain('const svgHeight = computed(() => {')
    expect(connectionCanvasFile).toContain('const svgWidth = computed(() => {')
    expect(connectionCanvasFile).toContain(':transform="contentTransform || undefined"')
    expect(connectionCanvasFile).toContain('v-for="layer in renderLayers"')
    expect(connectionCanvasFile).toContain(':style="{ zIndex: layer.zIndex }"')
    expect(connectionCanvasFile).toContain(':stroke-dasharray="getStrokeDasharray(line)"')
    expect(connectionCanvasFile).toContain(':height="svgHeight"')
    expect(connectionCanvasFile).toContain(':width="svgWidth"')
  })
})
