import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('diagram GPU shell entities source', () => {
  it('restores the rich entities browser in the GPU shell', () => {
    const shellFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')

    expect(shellFile).toContain('const entitySearchQuery: Ref<string> = ref(\'\')')
    expect(shellFile).toContain('const browserItemActionButtonBaseClass = \'inline-flex shrink-0 items-center justify-center px-2 leading-none\'')
    expect(shellFile).toContain('const browserItemActionRailClass = \'grid w-[3.5rem] shrink-0 content-start justify-items-stretch gap-1\'')
    expect(shellFile).toContain('const browserItemRowGridClass = \'grid grid-cols-[minmax(0,1fr)_3.5rem] items-start gap-2\'')
    expect(shellFile).toContain('const browserItemCompactRowGridClass = \'grid grid-cols-[minmax(0,1fr)_6.25rem] items-start gap-2\'')
    expect(shellFile).toContain('const syncDiagramViewSettings = (settings: DiagramViewSettings | null | undefined) => {')
    expect(shellFile).toContain('emit(\'updateDiagramViewSettings\', settings)')
    expect(shellFile).toContain('const showExecutableObjects: Ref<boolean> = ref(true)')
    expect(shellFile).toContain('const showTableFields: Ref<boolean> = ref(true)')
    expect(shellFile).toContain('watch([showExecutableObjects, showTableFields], () => {')
    expect(shellFile).toContain('syncLayoutStates()')
    expect(shellFile).toContain('data-diagram-view-select="desktop"')
    expect(shellFile).toContain('data-diagram-view-create="desktop"')
    expect(shellFile).toContain('data-diagram-view-delete="desktop"')
    expect(shellFile).toContain('data-executable-objects-toggle="true"')
    expect(shellFile).toContain('data-table-fields-toggle="true"')
    expect(shellFile).toContain('View')
    expect(shellFile).toContain('Execs')
    expect(shellFile).toContain('Fields')
    expect(shellFile).toContain('const buildBrowserTableItem = (table: PgmlSchemaModel[\'tables\'][number]): EntityBrowserItem => {')
    expect(shellFile).toContain('const filteredGroupedBrowserItems = computed(() => {')
    expect(shellFile).toContain('const toggleBrowserItemVisibility = (item: EntityBrowserItem) => {')
    expect(shellFile).toContain('const focusBrowserItemSource = (item: EntityBrowserItem) => {')
    expect(shellFile).toContain('data-entity-search="true"')
    expect(shellFile).toContain('data-browser-entity-row="groupItem.id"')
    expect(shellFile).toContain('data-browser-visibility-toggle="tableItem.id"')
    expect(shellFile).toContain('class="break-words text-[0.72rem] font-medium leading-5"')
    expect(shellFile).toContain('Standalone Objects')
    expect(shellFile).toContain('No entities match the current search.')
    expect(shellFile).toContain('.pgml-browser-search-match-row')
    expect(shellFile).toContain('.pgml-browser-search-match-text')
  })
})
