import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('diagram compare panel source', () => {
  it('renders a dedicated compare inspector and syncs it with the diagram shell', () => {
    const shellFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const comparePanelFile = readSourceFile('app/components/pgml/PgmlDiagramComparePanel.vue')
    const compareListFile = readSourceFile('app/components/pgml/PgmlDiagramCompareEntryList.vue')
    const compareExpansionFile = readSourceFile('app/components/pgml/PgmlDiagramCompareEntryExpansion.vue')
    const migrationsPanelFile = readSourceFile('app/components/pgml/PgmlDiagramMigrationsPanel.vue')
    const versionsPanelFile = readSourceFile('app/components/pgml/PgmlDiagramVersionsPanel.vue')

    expect(shellFile).toContain('const selectedCompareEntryId: Ref<string | null> = ref(null)')
    expect(shellFile).toContain('const isCompareDiagramActive = computed(() => {')
    expect(shellFile).toContain('const compareGhostOverlays = computed<DiagramCompareGhostOverlay[]>(() => {')
    expect(shellFile).toContain('const selectedDiagramCompareEntryIds = computed(() => {')
    expect(shellFile).toContain('const openComparator = () => {')
    expect(shellFile).toContain('data-diagram-tool-toggle="compare"')
    expect(shellFile).toContain('data-diagram-tool-toggle="migrations"')
    expect(shellFile).toContain('data-diagram-tool-toggle="versions"')
    expect(shellFile).toContain('data-diagram-tool-panel="true"')
    expect(shellFile).toContain(':data-diagram-tool-panel-expanded="isToolPanelViewportExpanded ? \'true\' : \'false\'"')
    expect(shellFile).toContain('data-diagram-tool-panel-tab="compare"')
    expect(shellFile).toContain('data-diagram-tool-panel-tab="migrations"')
    expect(shellFile).toContain('data-diagram-tool-panel-tab="versions"')
    expect(shellFile).toContain('const isToolPanelViewportExpanded = computed(() => {')
    expect(shellFile).toContain('const toggleToolPanelViewportExpanded = () => {')
    expect(shellFile).toContain('if (isMobileCanvasShell.value || isDesktopToolPanelViewportExpanded.value) {')
    expect(shellFile).toContain('return \'absolute inset-0 z-[5] grid min-h-0 w-full grid-rows-[auto_auto_minmax(0,1fr)] overflow-hidden border\'')
    expect(shellFile).toContain('return \'Compare changes\'')
    expect(shellFile).toContain('return `${compareEntries.length} highlighted change${compareEntries.length === 1 ? \'\' : \'s\'} between ${compareBaseLabel} and ${compareTargetLabel}.`')
    expect(shellFile).toContain('grid grid-cols-3 border-b border-[color:var(--studio-divider)]')
    expect(shellFile).toContain('<PgmlDiagramComparePanel')
    expect(shellFile).toContain(':comparison-items="compareComparisonItems"')
    expect(shellFile).toContain(':compare-base-id="versionCompareBaseId"')
    expect(shellFile).toContain(':compare-noise-filters="compareNoiseFilters"')
    expect(shellFile).toContain(':compare-options="versionCompareOptions"')
    expect(shellFile).toContain(':compare-target-id="versionCompareTargetId"')
    expect(shellFile).toContain(':excluded-labels="compareExcludedLabels"')
    expect(shellFile).toContain(':excluded-summary="compareExcludedSummary"')
    expect(shellFile).toContain(':hidden-excluded-label-count="compareHiddenExcludedLabelCount"')
    expect(shellFile).toContain(':selected-comparison-id="compareSelectedComparisonId"')
    expect(shellFile).toContain('@create-comparison="emit(\'createCompareComparison\')"')
    expect(shellFile).toContain('@edit-comparison-exclusions="emit(\'editCompareExclusions\')"')
    expect(shellFile).toContain('@select-comparison="emit(\'selectCompareComparison\', $event)"')
    expect(shellFile).toContain('@update:compare-base-id="emit(\'updateVersionCompareBaseId\', $event)"')
    expect(shellFile).toContain('@update:compare-noise-filters="emit(\'updateCompareNoiseFilters\', $event)"')
    expect(shellFile).toContain('@update:compare-target-id="emit(\'updateVersionCompareTargetId\', $event)"')
    expect(shellFile).toContain('data-diagram-tool-panel-actions="true"')
    expect(shellFile).toContain('data-diagram-tool-panel-expand="true"')
    expect(shellFile).toContain('<PgmlDiagramMigrationsPanel')
    expect(shellFile).toContain('<PgmlDiagramVersionsPanel')
    expect(shellFile).toContain('data-compare-ghost-entry="overlay.entryId"')

    expect(comparePanelFile).toContain('data-diagram-compare-panel="true"')
    expect(comparePanelFile).toContain('class="flex h-full min-h-0 min-w-0 flex-col overflow-hidden"')
    expect(comparePanelFile).toContain('data-studio-scrollable="true"')
    expect(comparePanelFile).toContain('data-compare-comparison-select="true"')
    expect(comparePanelFile).toContain('data-compare-create-comparison="true"')
    expect(comparePanelFile).toContain('data-compare-rename-comparison="true"')
    expect(comparePanelFile).toContain('data-compare-delete-comparison="true"')
    expect(comparePanelFile).toContain('lg:grid-cols-[minmax(0,1fr)_auto_auto_auto] lg:items-end')
    expect(comparePanelFile).toContain('data-compare-base-select="true"')
    expect(comparePanelFile).toContain('data-compare-export-html="true"')
    expect(comparePanelFile).toContain('data-compare-export-md="true"')
    expect(comparePanelFile).toContain('data-compare-noise-filter="option.key"')
    expect(comparePanelFile).toContain('data-compare-target-select="true"')
    expect(comparePanelFile).toContain('data-compare-search="true"')
    expect(comparePanelFile).toContain('data-compare-entity-filter="option.value"')
    expect(comparePanelFile).toContain('data-compare-entity-filter-marker="option.value"')
    expect(comparePanelFile).toContain('data-compare-entity-filter-count="option.value"')
    expect(comparePanelFile).toContain('data-compare-edit-exclusions="true"')
    expect(comparePanelFile).toContain('data-compare-stat-filter="statKind"')
    expect(comparePanelFile).toContain(':data-compare-detail-view="option.value"')
    expect(comparePanelFile).toContain('const compareStatLabelClass = \'font-mono text-[0.58rem] uppercase tracking-[0.08em]\'')
    expect(comparePanelFile).toContain('const compareEntityFilterButtonClass = \'inline-flex items-center gap-1.5 border px-2 py-1 font-mono text-[0.56rem] uppercase tracking-[0.08em] transition-colors duration-150 cursor-default\'')
    expect(comparePanelFile).toContain('const compareEntityFilterCountClass = \'border px-1 py-0.5 text-[0.48rem] leading-none transition-colors duration-150\'')
    expect(comparePanelFile).toContain('const compareOverviewSectionClass = \'grid min-w-0 gap-3 border-b border-[color:var(--studio-divider)] pb-3\'')
    expect(comparePanelFile).toContain('const compareDividerSectionClass = \'grid min-w-0 gap-3 border-t border-[color:var(--studio-divider)] pt-3\'')
    expect(comparePanelFile).toContain('const exclusionChipClass = \'border border-[color:var(--studio-divider)] px-1.5 py-0.5 font-mono text-[0.52rem] uppercase tracking-[0.08em] text-[color:var(--studio-shell-muted)]\'')
    expect(comparePanelFile).toContain('const compareNoiseFilterButtonClass = \'inline-flex items-center gap-2 px-2 py-1 font-mono text-[0.56rem] uppercase tracking-[0.08em] cursor-default\'')
    expect(comparePanelFile).toContain('const currentComparisonOptionValue = \'__current__\'')
    expect(comparePanelFile).toContain('type PgmlCompareStatKind = \'added\' | \'modified\' | \'removed\'')
    expect(comparePanelFile).toContain('type PgmlCompareNoiseFilterKey = keyof PgmlCompareNoiseFilters')
    expect(comparePanelFile).toContain('type PgmlCompareEntityFilterOption = {')
    expect(comparePanelFile).toContain('type PgmlCompareDetailViewMode = \'both\' | \'snapshot\' | \'structured\'')
    expect(comparePanelFile).toContain('type PgmlCompareNoiseFilterOption = {')
    expect(comparePanelFile).toContain('const compareEntityKindOrder: PgmlDiagramCompareEntityKind[] = [')
    expect(comparePanelFile).toContain('const compareEntityFilterLabelByKind: Readonly<Record<PgmlDiagramCompareEntityKind, string>> = Object.freeze({')
    expect(comparePanelFile).toContain('const compareStatKinds: PgmlCompareStatKind[] = [\'added\', \'modified\', \'removed\']')
    expect(comparePanelFile).toContain('const compareDetailViewOptions: PgmlCompareDetailViewOption[] = [')
    expect(comparePanelFile).toContain('const compareNoiseFilterOptions: PgmlCompareNoiseFilterOption[] = [')
    expect(comparePanelFile).toContain('const selectedChangeKinds: Ref<PgmlCompareStatKind[]> = ref([])')
    expect(comparePanelFile).toContain('const selectedEntityKinds: Ref<PgmlDiagramCompareEntityKind[]> = ref([])')
    expect(comparePanelFile).toContain('const detailViewMode: Ref<PgmlCompareDetailViewMode> = ref(\'structured\')')
    expect(comparePanelFile).toContain('const hasExcludedEntities = computed(() => {')
    expect(comparePanelFile).toContain('const comparisonSelectOptions = computed(() => {')
    expect(comparePanelFile).toContain('const resolveCompareVersionLabel = (')
    expect(comparePanelFile).toContain('const showFieldDiffs = computed(() => {')
    expect(comparePanelFile).toContain('const showSnapshotDiff = computed(() => {')
    expect(comparePanelFile).toContain('const orderedSelectedChangeKinds = computed(() => {')
    expect(comparePanelFile).toContain('const hasSelectedChangeKindFilters = computed(() => {')
    expect(comparePanelFile).toContain('const normalizedSearchQuery = computed(() => {')
    expect(comparePanelFile).toContain('const compareEntityFilterOptions = computed<PgmlCompareEntityFilterOption[]>(() => {')
    expect(comparePanelFile).toContain('const visibleContextEntries = computed(() => {')
    expect(comparePanelFile).toContain('const toggleCompareStatFilter = (kind: PgmlCompareStatKind) => {')
    expect(comparePanelFile).toContain('const buildVisibleChangeFilterLabel = (changeKinds: PgmlCompareStatKind[]) => {')
    expect(comparePanelFile).toContain('const toggleCompareEntityKindFilter = (kind: PgmlDiagramCompareEntityKind) => {')
    expect(comparePanelFile).toContain('const toggleCompareNoiseFilter = (key: PgmlCompareNoiseFilterKey) => {')
    expect(comparePanelFile).toContain('const getCompareEntityFilterButtonStyle = (kind: PgmlDiagramCompareEntityKind) => {')
    expect(comparePanelFile).toContain('const getCompareEntityFilterMarkerStyle = (kind: PgmlDiagramCompareEntityKind) => {')
    expect(comparePanelFile).toContain('const getCompareEntityFilterCountStyle = (kind: PgmlDiagramCompareEntityKind) => {')
    expect(comparePanelFile).toContain('const getCompareNoiseFilterButtonClass = (key: PgmlCompareNoiseFilterKey) => {')
    expect(comparePanelFile).toContain('const updateSelectedComparisonId = (value: unknown) => {')
    expect(comparePanelFile).toContain('const updateCompareBaseId = (value: unknown) => {')
    expect(comparePanelFile).toContain('const updateCompareTargetId = (value: unknown) => {')
    expect(comparePanelFile).toContain('const buildCompareExportInput = (): PgmlCompareExportInput => {')
    expect(comparePanelFile).toContain('const downloadCompareExportHtml = () => {')
    expect(comparePanelFile).toContain('const downloadCompareExportMarkdown = () => {')
    expect(comparePanelFile).toContain('v-for="option in compareDetailViewOptions"')
    expect(comparePanelFile).toContain('v-for="option in compareNoiseFilterOptions"')
    expect(comparePanelFile).toContain('v-for="option in compareEntityFilterOptions"')
    expect(comparePanelFile).toContain('@click="toggleCompareStatFilter(statKind)"')
    expect(comparePanelFile).toContain('@click="toggleCompareEntityKindFilter(option.value)"')
    expect(comparePanelFile).toContain('@click="toggleCompareNoiseFilter(option.key)"')
    expect(comparePanelFile).toContain('@click="downloadCompareExportHtml"')
    expect(comparePanelFile).toContain('@click="downloadCompareExportMarkdown"')
    expect(comparePanelFile).toContain('@click="emit(\'edit-comparison-exclusions\')"')
    expect(comparePanelFile).toContain('@click="clearFilters"')
    expect(comparePanelFile).toContain('v-if="visibleContextEntries.length > 0"')
    expect(comparePanelFile).toContain('<PgmlDiagramCompareEntryList')
    expect(comparePanelFile).toContain(':show-field-diffs="showFieldDiffs"')
    expect(comparePanelFile).toContain(':show-snapshot-diff="showSnapshotDiff"')
    expect(comparePanelFile).toContain('selectedDiagramContextIds')
    expect(comparePanelFile).toContain('No compare exclusions are stored for')
    expect(comparePanelFile).not.toContain('compareFilterOptions')
    expect(comparePanelFile).not.toContain('studioPanelSurfaceClass')
    expect(comparePanelFile).not.toContain('Before snapshot')
    expect(comparePanelFile).not.toContain('After snapshot')

    expect(compareListFile).toContain('const listItems = computed<PgmlDiagramCompareEntryListItem[]>(() => {')
    expect(compareListFile).toContain('const shouldGroupScope = entry.scopeKind === \'table\' && scopeEntries.length > 1')
    expect(compareListFile).toContain(':data-compare-scope-row="item.scopeId"')
    expect(compareListFile).toContain(':data-compare-scope-entry="item.scopeId"')
    expect(compareListFile).toContain('scopeLabel: scopeEntries.find(scopeEntry => scopeEntry.entityKind === \'table\')?.label || entry.scopeLabel')
    expect(compareListFile).toContain('showFieldDiffs = true')
    expect(compareListFile).toContain('showSnapshotDiff = false')
    expect(compareListFile).toContain('v-bind="buildEntryRowAttributes(entry.id)"')
    expect(compareListFile).toContain('v-bind="buildEntryButtonAttributes(entry.id)"')
    expect(compareListFile).toContain('[overflow-wrap:anywhere]')
    expect(compareListFile).toContain('On diagram')

    expect(compareExpansionFile).toContain('data-compare-entry-detail="true"')
    expect(compareExpansionFile).toContain('showFieldDiffs = true')
    expect(compareExpansionFile).toContain('showSnapshotDiff = false')
    expect(compareExpansionFile).toContain('class="grid gap-3 border-t border-[color:var(--studio-divider)] px-3 py-3"')
    expect(compareExpansionFile).toContain('label="Show on diagram"')
    expect(compareExpansionFile).toContain('label="Focus source"')
    expect(compareExpansionFile).toContain('buildPgmlCompareDiffLines')
    expect(compareExpansionFile).toContain('data-compare-diff-block="true"')
    expect(compareExpansionFile).toContain('data-compare-diff-legend="removed"')
    expect(compareExpansionFile).toContain('data-compare-diff-legend="added"')
    expect(compareExpansionFile).toContain(':data-compare-diff-kind="line.kind"')
    expect(compareExpansionFile).toContain('Structured diff')
    expect(compareExpansionFile).toContain('Snapshot diff')
    expect(compareExpansionFile).toContain('v-if="showFieldDiffs && entry.fields.length > 0"')
    expect(compareExpansionFile).toContain('v-if="showSnapshotDiff"')
    expect(compareExpansionFile).toContain('{{ baseLabel }}')
    expect(compareExpansionFile).toContain('{{ targetLabel }}')
    expect(compareExpansionFile).not.toContain('{{ entry.label }}')
    expect(compareExpansionFile).not.toContain('{{ entry.description }}')
    expect(compareExpansionFile).not.toContain('Before snapshot')
    expect(compareExpansionFile).not.toContain('After snapshot')

    expect(migrationsPanelFile).toContain('data-diagram-migrations-panel="true"')
    expect(migrationsPanelFile).toContain('data-version-migration-format="sql"')
    expect(migrationsPanelFile).toContain('data-version-migration-download="activeMigrationFormat"')

    expect(versionsPanelFile).toContain('data-diagram-versions-panel="true"')
    expect(versionsPanelFile).toContain('Version Switcher')
    expect(versionsPanelFile).toContain(':data-version-view="version.id"')
    expect(versionsPanelFile).toContain(':data-version-restore="version.id"')
    expect(versionsPanelFile).not.toContain('data-version-open-comparator="true"')
    expect(versionsPanelFile).not.toContain('data-version-open-migrations="true"')
    expect(versionsPanelFile).not.toContain(':data-version-compare-base="version.id"')
    expect(versionsPanelFile).not.toContain(':data-version-compare-target="version.id"')
  })
})
