import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('diagram versions panel source', () => {
  it('uses migration change metadata instead of raw SQL text length to enable export actions', () => {
    const file = readSourceFile('app/components/pgml/PgmlDiagramVersionsPanel.vue')

    expect(file).toContain('migrationHasChanges = false')
    expect(file).toContain('const hasMigrationSql = computed(() => migrationHasChanges && migrationSql.trim().length > 0)')
    expect(file).toContain('const hasMigrationKysely = computed(() => migrationHasChanges && migrationKysely.trim().length > 0)')
    expect(file).toContain('type PgmlMigrationFormat = \'sql\' | \'kysely\'')
    expect(file).toContain('type PgmlVersionMigrationArtifact = {')
    expect(file).toContain('const activeMigrationFormat: Ref<PgmlMigrationFormat> = ref(\'sql\')')
    expect(file).toContain('const migrationArtifacts = computed<Record<PgmlMigrationFormat, PgmlVersionMigrationArtifact>>(() => {')
    expect(file).toContain('const activeMigrationArtifact = computed(() => {')
    expect(file).toContain('const versionStatCards = computed(() => {')
    expect(file).toContain('label: \'Locked\'')
    expect(file).toContain('label: \'Design\'')
    expect(file).toContain('label: \'Impl\'')
    expect(file).toContain('v-for="stat in versionStatCards"')
    expect(file).toContain('label="Kysely"')
    expect(file).toContain('activeMigrationFormat = \'kysely\'')
    expect(file).toContain('return activeMigrationArtifact.value.label')
    expect(file).toContain('return activeMigrationArtifact.value.content')
    expect(file).toContain('return activeMigrationArtifact.value.hasChanges')
    expect(file).toContain('return activeMigrationArtifact.value.mimeType')
    expect(file).toContain('No forward ${activeMigrationLabel.toLowerCase()} migration generated yet.')
    expect(file).toContain('compareRelationshipSummary')
    expect(file).toContain('Path: {{ version.lineageLabel }}')
    expect(file).toContain('Branch root: {{ version.branchRootLabel }}')
    expect(file).toContain('Leaf')
    expect(file).toContain('const buildVersionMetricBadges = (version: PgmlVersionPanelItem) => {')
    expect(file).toContain('buildCountLabel(version.childCount, \'branch\', \'branches\')')
    expect(file).toContain('buildCountLabel(version.siblingCount, \'sibling\')')
    expect(file).toContain('buildCountLabel(version.descendantCount, \'descendant\')')
    expect(file).toContain('buildCountLabel(version.ancestorCount, \'ancestor\')')
    expect(file).toContain('appendMetricBadge(badges, `Branch size ${version.branchVersionCount}`)')
    expect(file).toContain('appendMetricBadge(badges, `Branch leaves ${version.branchLeafCount}`)')
    expect(file).toContain('appendMetricBadge(badges, `Branch depth ${version.branchMaxDepth}`)')
    expect(file).toContain('v-for="badge in buildVersionMetricBadges(version)"')
    expect(file).toContain('Latest overall')
    expect(file).toContain('Latest {{ version.role }}')
    expect(file).toContain('const comparePresetButtons = computed(() => {')
    expect(file).toContain('label: \'Workspace base to draft\'')
    expect(file).toContain('label: \'Latest to draft\'')
    expect(file).toContain('Latest impl to draft')
    expect(file).toContain('Latest design to draft')
    expect(file).toContain('v-for="preset in comparePresetButtons"')
    expect(file).toContain(':disabled="previewTargetId === version.id"')
  })
})
