import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('diagram performance source', () => {
  it('limits GPU plane promotion to active viewport interactions', () => {
    const benchmarkFile = readSourceFile('scripts/benchmark-diagram-fps.ts')
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const pageFile = readSourceFile('app/components/studio/StudioWorkspacePage.vue')
    const sceneFile = readSourceFile('app/components/pgml/PgmlDiagramGpuScene.vue')

    expect(canvasFile).toContain('const routedConnectionLines: Ref<DiagramGpuConnectionLine[]> = ref([])')
    expect(canvasFile).toContain('const activeConnectionDragPreview: Ref<ActiveConnectionDragPreview | null> = ref(null)')
    expect(canvasFile).toContain('const liveConnectionPreviewLines: Ref<DiagramGpuConnectionLine[]> = ref([])')
    expect(canvasFile).toContain('let liveSceneConnectionDragPreview: ActiveConnectionDragPreview | null = null')
    expect(canvasFile).toContain('const rendererBackend: Ref<DiagramRendererBackend> = ref(getInitialRendererBackendPreference())')
    expect(canvasFile).toContain('data-diagram-renderer-select="desktop"')
    expect(canvasFile).toContain('data-diagram-renderer-select="mobile"')
    expect(canvasFile).toContain('@renderer-capability-change="handleRendererCapabilityChange"')
    expect(canvasFile).toContain('const styledConnectionLines = computed(() => {')
    expect(canvasFile).toContain('const automationConnectionCanvasLayers = computed(() => {')
    expect(canvasFile).toContain('buildDiagramConnectionPreviewLayers(')
    expect(canvasFile).toContain('const forceGpuScene = windowWithDebugFlag.__PGML_FORCE_GPU_SCENE__ === true')
    expect(canvasFile).toContain('shouldRenderAutomationPlane.value = !forceGpuScene && (')
    expect(benchmarkFile).toContain('__PGML_FORCE_GPU_SCENE__')
    expect(benchmarkFile).toContain('forceGpuScene: true')
    expect(canvasFile).toContain('let routingWorker: Worker | null = null')
    expect(canvasFile).toContain('new Worker(new URL(\'../../workers/diagram-routing.worker.ts\', import.meta.url), {')
    expect(canvasFile).toContain('const activeRoutingBackend: Ref<DiagramRoutingBackend> = ref(\'cpu\')')
    expect(canvasFile).toContain('const shouldPreferMainThreadConnectionRouting: Ref<boolean> = ref(false)')
    expect(canvasFile).toContain('preserveDragPreviewUntilSettled?: boolean')
    expect(canvasFile).toContain('import { routeDiagramConnectionsWithCpu } from \'~/workers/diagram-routing.worker\'')
    expect(canvasFile).toContain('const webgpuLines = await tryComputeConnectionLinesWithWebgpu(routingRequest, requestId)')
    expect(canvasFile).toContain('if (webgpuLines && webgpuLines.length > 0) {')
    expect(canvasFile).toContain('if (webgpuLines && webgpuLines.length > 0 && !options.preserveDragPreviewUntilSettled && requestId === latestConnectionRequestId) {')
    expect(canvasFile).toContain('const clearPreservedDragPreview = () => {')
    expect(canvasFile).toContain('const computeLiveConnectionPreviewLines = async (')
    expect(canvasFile).toContain('const scheduleLiveConnectionPreview = (preview: DiagramNodeDragPreview) => {')
    expect(canvasFile).toContain('const nextLines = await routeDiagramConnectionsWithWebgpu(request)')
    expect(canvasFile).toContain('activeRoutingBackend.value = \'webgpu\'')
    expect(canvasFile).toContain('activeRoutingBackend.value = \'cpu\'')
    expect(canvasFile).toContain('const buildMainThreadFallbackConnectionLines = (')
    expect(canvasFile).toContain('if (shouldPreferMainThreadConnectionRouting.value) {')
    expect(canvasFile).toContain('const lines = routeDiagramConnectionsWithCpu(routingRequest)')
    expect(canvasFile).toContain('return lines.length > 0 ? lines : buildMainThreadFallbackConnectionLines(routingRequest)')
    expect(canvasFile).toContain('commitSettledLines(buildMainThreadFallbackConnectionLines(routingRequest), \'cpu\')')
    expect(canvasFile).toContain('const routingRequest = buildConnectionRoutingRequest(descriptors, requestId)')
    expect(canvasFile).toContain('worker.postMessage(request)')
    expect(canvasFile).toContain('const commitSettledLines = (nextLines: DiagramGpuConnectionLine[], backend: DiagramRoutingBackend) => {')
    expect(canvasFile).toContain('routedConnectionLines.value = nextLines')
    expect(canvasFile).toContain('const getReferenceTargetGeometry = (')
    expect(canvasFile).toContain('return routingGeometry.columnGeometry.get(getColumnAnchorKey(tableId, columnName))')
    expect(canvasFile).toContain('|| routingGeometry.tableGeometry.get(tableId)')
    expect(sceneFile).toContain('dragStarted?: boolean')
    expect(sceneFile).toContain('if (!dragSession.dragStarted && !movedEnoughToDrag) {')
    expect(sceneFile).toContain('const getDragWorldPosition = (session: DragSession, clientX: number, clientY: number) => {')
    expect(sceneFile).toContain('const getDragTargetForHitTarget = (target: HitTarget | null) => {')
    expect(sceneFile).toContain('buildDiagramConnectionDragPreviewPoints(')
    expect(sceneFile).toContain('if ((target.kind === \'table-header\' || target.kind === \'table-row\') && target.tableId) {')
    expect(sceneFile).toContain('if ((target.kind === \'object-header\' || target.kind === \'object-body\') && target.objectId) {')
    expect(sceneFile).toContain('dragSession.lastDragX = nextPosition.x')
    expect(sceneFile).toContain('dragSession.lastDragY = nextPosition.y')
    expect(sceneFile).toContain('const finalPosition = typeof dragSession.lastDragX === \'number\' && typeof dragSession.lastDragY === \'number\'')
    expect(sceneFile).toContain('const currentPreview: DiagramNodeDragPreview = {')
    expect(sceneFile).toContain('setDragPreview(currentPreview)')
    expect(sceneFile).toContain('setConnectionDragPreview(currentPreview)')
    expect(sceneFile).toContain('const getVisibleConnectionBuckets = (preview: DiagramConnectionPreviewDragState | null) => {')
    expect(sceneFile).toContain('let shouldDisableConnectionCulling = false')
    expect(sceneFile).toContain('const visibleConnectionIds = shouldDisableConnectionCulling')
    expect(sceneFile).toContain('staticLineGraphics = new pixi.Graphics()')
    expect(sceneFile).toContain('dynamicLineGraphics = new pixi.Graphics()')
    expect(sceneFile).not.toContain('const getConnectionStrokeScale = () => {')
    expect(sceneFile).not.toContain('const strokeScale = getConnectionStrokeScale()')
    expect(sceneFile).toContain('const dashPattern = parseDashPattern(line.dashPattern)')
    expect(sceneFile).toContain('width: line.dashed ? 1.02 : 1.08')
    expect(sceneFile).toContain('width: line.animated ? 1.34 : 1.02')
    expect(sceneFile).toContain('const destroyTextureEntry = (')
    expect(sceneFile).toContain('const pruneTextureEntries = (')
    expect(sceneFile).toContain('pruneTextureEntries(tableSpriteEntries, tableIds)')
    expect(sceneFile).toContain('tableSpriteCount: tableSpriteEntries.size')
    expect(sceneFile).toContain('const scheduleDragPreviewRender = () => {')
    expect(sceneFile).toContain('const setDragPreview = (preview: DiagramNodeDragPreview | null) => {')
    expect(sceneFile).toContain('const setConnectionDragPreview = (preview: DiagramConnectionPreviewDragState | null) => {')
    expect(sceneFile).toContain('includeStatic: false')
    expect(sceneFile).toContain('typedWindow.__PGML_ENABLE_SCENE_DEBUG__ !== true')
    expect(sceneFile).toContain('rendererBackend = \'auto\'')
    expect(sceneFile).toContain('rendererCapabilityChange: [capability: DiagramRendererCapability]')
    expect(sceneFile).toContain('const initialRendererCapability = getRendererCapabilitySnapshot()')
    expect(sceneFile).toContain('setRendererCapability(applyDiagramRendererInitFailure(initialRendererCapability))')
    expect(sceneFile).toContain('await restartPixi()')
    expect(sceneFile).toContain('shouldDisableConnectionCulling = /Android/i.test(navigator.userAgent) || window.matchMedia(\'(pointer: coarse)\').matches')
    expect(pageFile).toContain('new Worker(new URL(\'../../workers/pgml-analysis.worker.ts\', import.meta.url), {')
    expect(pageFile).toContain('const shouldBuildVersionArtifacts = computed(() => {')
    expect(pageFile).toContain('const compareMigrationBundle = computed(() => {')
  })

  it('batches wheel zoom steps to one viewport update per animation frame', () => {
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')

    expect(canvasFile).toContain('@wheel.stop')
    expect(canvasFile).toContain('@click="sceneRef?.zoomBy(-1)"')
    expect(canvasFile).toContain('@click="sceneRef?.zoomBy(1)"')
    expect(canvasFile).toContain('@click="sceneRef?.resetView()"')
  })

  it('coalesces drag follow-up work instead of queueing a fresh tick for every move', () => {
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const settledPreviewGuardIndex = canvasFile.indexOf('if (currentConnectionDragPreview && !options.preserveDragPreviewUntilSettled) {')
    const settledPreviewRequestIndex = canvasFile.indexOf('latestConnectionRequestId += 1')

    expect(canvasFile).toContain('const measureElementSize = (element: HTMLElement | null): MeasuredSize => {')
    expect(canvasFile).toContain('useResizeObserver(viewportRef, syncViewportSize)')
    expect(canvasFile).toContain('useResizeObserver(detailPopoverRef, syncDetailPopoverSize)')
    expect(canvasFile).toContain('const updateSceneDragPreview = (')
    expect(canvasFile).toContain('const commitSceneNodePosition = (')
    expect(canvasFile).toContain('const setSceneConnectionDragPreview = (preview: ActiveConnectionDragPreview | null) => {')
    expect(canvasFile).toContain('const setSceneDragPreview = (preview: DiagramNodeDragPreview | null) => {')
    expect(canvasFile).toContain('scheduleLiveConnectionPreview(nextPreview)')
    expect(canvasFile).toContain('const settledPreview: DiagramNodeDragPreview = {')
    expect(canvasFile).toContain('setSceneConnectionDragPreview(settledPreview)')
    expect(canvasFile).toContain('if (liveConnectionPreviewLines.value.length === 0) {')
    expect(canvasFile).toContain('lastDragX: node.x')
    expect(canvasFile).toContain('automationPlaneDragSession.lastDragX = automationPlaneDragSession.originX + deltaX')
    expect(canvasFile).toContain('x: automationPlaneDragSession.lastDragX')
    expect(canvasFile).toContain('const shouldStartAutomationPlaneGroupDrag = (')
    expect(canvasFile).toContain('const shouldStartAutomationPlaneNodeSurfaceDrag = (')
    expect(canvasFile).toContain('const handleAutomationPlaneGroupedTablePointerDown = (')
    expect(canvasFile).toContain('const handleAutomationPlaneGroupSurfacePointerDown = (')
    expect(canvasFile).toContain('const setAutomationNodeElement = (')
    expect(canvasFile).toContain('const applyAutomationNodeDragPreview = (preview: DiagramNodeDragPreview | null) => {')
    expect(canvasFile).toContain('@pointerdown="node.kind === \'group\' ? handleAutomationPlaneGroupSurfacePointerDown($event, node) : handleAutomationPlaneNodeSurfacePointerDown($event, node)"')
    expect(canvasFile).toContain(':data-group-surface="node.id"')
    expect(canvasFile).toContain(':data-object-collapse-button="node.id"')
    expect(canvasFile).toContain('preserveDragPreviewUntilSettled: true')
    expect(canvasFile).toContain('routingWorker?.terminate()')
    expect(settledPreviewGuardIndex).toBeGreaterThan(-1)
    expect(settledPreviewRequestIndex).toBeGreaterThan(-1)
    expect(settledPreviewGuardIndex).toBeLessThan(settledPreviewRequestIndex)
  })

  it('uses transform previews, live dragged-line rerouting, and viewport culling for static lines', () => {
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const pageFile = readSourceFile('app/components/studio/StudioWorkspacePage.vue')
    const sceneFile = readSourceFile('app/components/pgml/PgmlDiagramGpuScene.vue')

    expect(canvasFile).toContain('const viewportSize: Ref<MeasuredSize> = ref({')
    expect(canvasFile).toContain('const detailPopoverSize: Ref<MeasuredSize> = ref({')
    expect(canvasFile).toContain('const browserItemCompactActionButtonClass = getStudioStateButtonClass({')
    expect(canvasFile).toContain('const isMobileSurfaceView = computed(() => {')
    expect(canvasFile).toContain('const shouldShowZoomToolbar = computed(() => !isMobileSurfaceView.value)')
    expect(canvasFile).toContain('const displayedConnectionLines = computed(() => {')
    expect(canvasFile).toContain(':connections="displayedConnectionLines"')
    expect(canvasFile).toContain(':ref="(element) => setAutomationNodeElement(node.id, element)"')
    expect(canvasFile).toContain(':viewport-reset-key="viewportResetKey"')
    expect(canvasFile).toContain('const connectionStyleByKey = computed<Record<string, {')
    expect(sceneFile).toContain('setConnectionDragPreview,')
    expect(sceneFile).toContain('setDragPreview,')
    expect(pageFile).toContain(':commit-debounce-ms="editorCommitDebounceMs"')
    expect(pageFile).toContain(':diagnostics-delay-ms="editorDiagnosticsDelayMs"')
    expect(pageFile).toContain('@tool-panel-visibility-change="handleCanvasToolPanelVisibilityChange"')
  })
})
