import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('diagram performance source', () => {
  it('limits GPU plane promotion to active viewport interactions', () => {
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const pageFile = readSourceFile('app/pages/diagram.vue')
    const sceneFile = readSourceFile('app/components/pgml/PgmlDiagramGpuScene.vue')

    expect(canvasFile).toContain('const routedConnectionLines: Ref<DiagramGpuConnectionLine[]> = ref([])')
    expect(canvasFile).toContain('const activeConnectionDragPreview: Ref<ActiveConnectionDragPreview | null> = ref(null)')
    expect(canvasFile).toContain('const rendererBackend: Ref<DiagramRendererBackend> = ref(getInitialRendererBackendPreference())')
    expect(canvasFile).toContain('data-diagram-renderer-select="desktop"')
    expect(canvasFile).toContain('data-diagram-renderer-select="mobile"')
    expect(canvasFile).toContain('@renderer-capability-change="handleRendererCapabilityChange"')
    expect(canvasFile).toContain('const displayedConnectionLines = computed(() => {')
    expect(canvasFile).toContain('const styledConnectionLines = computed(() => {')
    expect(canvasFile).toContain('buildDiagramConnectionPreviewLayers(routedConnectionLines.value, activeDrag)')
    expect(canvasFile).toContain('let routingWorker: Worker | null = null')
    expect(canvasFile).toContain('new Worker(new URL(\'../../workers/diagram-routing.worker.ts\', import.meta.url), {')
    expect(canvasFile).toContain('const activeRoutingBackend: Ref<DiagramRoutingBackend> = ref(\'cpu\')')
    expect(canvasFile).toContain('preserveDragPreviewUntilSettled?: boolean')
    expect(canvasFile).toContain('const webgpuLines = await tryComputeConnectionLinesWithWebgpu(routingRequest, requestId)')
    expect(canvasFile).toContain('if (webgpuLines && !options.preserveDragPreviewUntilSettled && requestId === latestConnectionRequestId) {')
    expect(canvasFile).toContain('const clearPreservedDragPreview = () => {')
    expect(canvasFile).toContain('const nextLines = await routeDiagramConnectionsWithWebgpu(request)')
    expect(canvasFile).toContain('activeRoutingBackend.value = \'webgpu\'')
    expect(canvasFile).toContain('activeRoutingBackend.value = \'cpu\'')
    expect(canvasFile).toContain('const routingRequest = buildConnectionRoutingRequest(descriptors, requestId)')
    expect(canvasFile).toContain('worker.postMessage(routingRequest)')
    expect(canvasFile).toContain('const commitSettledLines = (nextLines: DiagramGpuConnectionLine[], backend: DiagramRoutingBackend) => {')
    expect(canvasFile).toContain('routedConnectionLines.value = nextLines')
    expect(sceneFile).toContain('dragStarted?: boolean')
    expect(sceneFile).toContain('if (!dragSession.dragStarted && !movedEnoughToDrag) {')
    expect(sceneFile).toContain('const getDragWorldPosition = (session: DragSession, clientX: number, clientY: number) => {')
    expect(sceneFile).toContain('const getDragTargetForHitTarget = (target: HitTarget | null) => {')
    expect(sceneFile).toContain('if ((target.kind === \'table-header\' || target.kind === \'table-row\') && target.tableId) {')
    expect(sceneFile).toContain('if ((target.kind === \'object-header\' || target.kind === \'object-body\') && target.objectId) {')
    expect(sceneFile).toContain('dragSession.lastDragX = nextPosition.x')
    expect(sceneFile).toContain('dragSession.lastDragY = nextPosition.y')
    expect(sceneFile).toContain('const finalPosition = typeof dragSession.lastDragX === \'number\' && typeof dragSession.lastDragY === \'number\'')
    expect(sceneFile).toContain('rendererBackend = \'auto\'')
    expect(sceneFile).toContain('rendererCapabilityChange: [capability: DiagramRendererCapability]')
    expect(sceneFile).toContain('const initialRendererCapability = getRendererCapabilitySnapshot()')
    expect(sceneFile).toContain('setRendererCapability(applyDiagramRendererInitFailure(initialRendererCapability))')
    expect(sceneFile).toContain('await restartPixi()')
    expect(pageFile).toContain('new Worker(new URL(\'../workers/pgml-analysis.worker.ts\', import.meta.url), {')
    expect(pageFile).toContain('const shouldBuildVersionArtifacts = computed(() => {')
    expect(pageFile).toContain('const compareMigrationBundle = computed(() => {')
  })

  it('batches wheel zoom steps to one viewport update per animation frame', () => {
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')

    expect(canvasFile).toContain('@wheel.stop')
    expect(canvasFile).toContain('@click="sceneRef?.zoomBy(-1)"')
    expect(canvasFile).toContain('@click="sceneRef?.zoomBy(1)"')
    expect(canvasFile).toContain('@click="sceneRef?.resetView()"')
  })

  it('coalesces drag follow-up work instead of queueing a fresh tick for every move', () => {
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')

    expect(canvasFile).toContain('const measureElementSize = (element: HTMLElement | null): MeasuredSize => {')
    expect(canvasFile).toContain('useResizeObserver(viewportRef, syncViewportSize)')
    expect(canvasFile).toContain('useResizeObserver(detailPopoverRef, syncDetailPopoverSize)')
    expect(canvasFile).toContain('const applySceneNodePosition = (')
    expect(canvasFile).toContain('lastDragX: node.x')
    expect(canvasFile).toContain('automationPlaneDragSession.lastDragX = automationPlaneDragSession.originX + deltaX')
    expect(canvasFile).toContain('x: automationPlaneDragSession.lastDragX')
    expect(canvasFile).toContain('const shouldStartAutomationPlaneGroupDrag = (')
    expect(canvasFile).toContain('const shouldStartAutomationPlaneNodeSurfaceDrag = (')
    expect(canvasFile).toContain('const handleAutomationPlaneGroupedTablePointerDown = (')
    expect(canvasFile).toContain('const handleAutomationPlaneGroupSurfacePointerDown = (')
    expect(canvasFile).toContain('@pointerdown="node.kind === \'group\' ? handleAutomationPlaneGroupSurfacePointerDown($event, node) : handleAutomationPlaneNodeSurfacePointerDown($event, node)"')
    expect(canvasFile).toContain(':data-group-surface="node.id"')
    expect(canvasFile).toContain(':data-object-collapse-button="node.id"')
    expect(canvasFile).toContain('preserveDragPreviewUntilSettled: true')
    expect(canvasFile).toContain('routingWorker?.terminate()')
  })

  it('uses transform previews, live dragged-line rerouting, and viewport culling for static lines', () => {
    const canvasFile = readSourceFile('app/components/pgml/PgmlDiagramCanvasGpuShell.vue')
    const pageFile = readSourceFile('app/pages/diagram.vue')

    expect(canvasFile).toContain('const viewportSize: Ref<MeasuredSize> = ref({')
    expect(canvasFile).toContain('const detailPopoverSize: Ref<MeasuredSize> = ref({')
    expect(canvasFile).toContain('const browserItemCompactActionButtonClass = getStudioStateButtonClass({')
    expect(canvasFile).toContain('const isMobileSurfaceView = computed(() => {')
    expect(canvasFile).toContain('const shouldShowZoomToolbar = computed(() => !isMobileSurfaceView.value)')
    expect(canvasFile).toContain(':connections="styledConnectionLines"')
    expect(canvasFile).toContain(':viewport-reset-key="viewportResetKey"')
    expect(canvasFile).toContain('const connectionStyleByKey = computed<Record<string, {')
    expect(pageFile).toContain(':commit-debounce-ms="editorCommitDebounceMs"')
    expect(pageFile).toContain(':diagnostics-delay-ms="editorDiagnosticsDelayMs"')
    expect(pageFile).toContain('@tool-panel-visibility-change="handleCanvasToolPanelVisibilityChange"')
  })
})
