import { describe, expect, it } from 'vitest'
import { readSourceFile } from './source-test-utils'

describe('Index page source', () => {
  it('wires the browser and computer-file launch flows while keeping hosted database unfinished', () => {
    const file = readSourceFile('app/pages/index.vue')

    expect(file).toContain('const sourceCards = computed<SourceCardDefinition[]>(() => {')
    expect(file).toContain('useStudioSessionStore')
    expect(file).toContain('useStudioSourcesStore')
    expect(file).toContain('storeToRefs(studioSourcesStore)')
    expect(file).toContain('loadRecentComputerPgmlFile')
    expect(file).toContain('openComputerPgmlFile')
    expect(file).toContain('createComputerPgmlFile')
    expect(file).toContain('buildBrowserStudioExampleQuery')
    expect(file).toContain('buildBrowserStudioNewQuery')
    expect(file).toContain('buildBrowserStudioSavedQuery')
    expect(file).toContain('buildFileStudioRecentQuery')
    expect(file).toContain('studioSessionStore.authorizeLaunchAccess()')
    expect(file).toContain('studioSessionStore.primePreloadedFileLaunch(')
    expect(file).toContain('studioSourcesStore.refreshBrowserSchemas()')
    expect(file).toContain('studioSourcesStore.refreshRecentComputerFiles()')
    expect(file).toContain('onBeforeRouteLeave((to) => {')
    expect(file).toContain('delete-saved-schema')
    expect(file).toContain('delete-recent-computer-file')
    expect(file).toContain('computerFileAccessDialogOpen')
    expect(file).toContain('Allow computer file access')
    expect(file).toContain('@action="handleSourceCardAction"')
    expect(file).toContain('const specBannerButtonClass = studioButtonClasses.ghost')
    expect(file).toContain('data-spec-banner="true"')
    expect(file).toContain('sqlDumpDescription')
    expect(file).toContain('Choose a .pgml file from your computer')
    expect(file).toContain('Hosted database')
  })
})
